### ISSUE TITLE
Add layout specific class to body class tag

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#114]
or is there another way, to bind styles to a specific layout (besides adding an additional wrapper div)?

**Comment by datakurre** [comment]
+1 should be somewhat possible in our transform fiddling with body tag

agitator kirjoitti ke elokuuta 12 11:55:55 2015 GMT+0300:

**Comment by datakurre** [comment]
Implemented in 1.0b4 as far as currently possible. (Layout name is lost when layout customized, yet it might be even more misleading to preserve it, because custom layout could be whatever.)
