### ISSUE TITLE
Title field tile allows linebreaks event is shouldn't

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#115]
Either allow line breaks in titles and support it or don't allow and prevent the user from entering.

**Comment by datakurre** [comment]
Preventing them would be the correct answer, but may no be trivial, because even title tile uses TinyMCE. I wonder, if br tags could be hidden with CSS so that it would look like line breaks are prevented.

agitator kirjoitti ke elokuuta 12 12:05:10 2015 GMT+0300:

**Comment by datakurre** [comment]
Should check if tinymce could be configured to disallow linebreaks (ans other formatting) for fields which schema is textline?

**Comment by vangheem** [comment]
This is fixed.
