### ISSUE TITLE
Changing assignments in layout control panel not working

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#116]
changing the content layout within assignment changes the values in portal_types/Event/Aliases

from 
++layout++default  |  ++contentlayout++mytheme/event.html

to
++layout++default-event  |  ++contentlayout++mytheme/event.html

and adds and empty 
++layout++default

**Comment by datakurre** [comment]
There might be some reason for that. Yet, this part is moving target since we (me and Nathan) are both figuring out the correct way to support switchable and partially editable layouts.
 
agitator kirjoitti ke elokuuta 12 12:07:13 2015 GMT+0300:

**Comment by vangheem** [comment]
Yes, this whole process is being worked on. See https://github.com/plone/plone.app.mosaic/issues/108

**Comment by agitator** [comment]
just wanted it to be known ;-)
