### ISSUE TITLE
plone.protect warnings are appearing

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#117]
@datakurre said: "the issues is probably in drafting support in plone.app.tiles. Viewing page with tiles may do something to update (timestamp?) existing draft, which triggers that."

**Comment by vangheem** [comment]
Make sure Plone.subrequest is checked out. One issue I fixed was due to sub
requests.

**Comment by datakurre** [comment]
Just have to say that while that automatic CSRF feels annoying (enforces to fix things), it's really cool.

**Comment by datakurre** [comment]
Ok. Hopefully it was that. Did not see obvious issues by just re-reading p.a.tiles drafting code.

**Comment by datakurre** [comment]
I assume these are fixed in plone.protect.
