### ISSUE TITLE
heroku deploy fails

### ISSUE THREAD

**Issue by pabo3000** [plone/plone.app.mosaic#129]
```
...
...
...
Got plone.app.standardtiles 1.0b1.
Getting distribution for 'plone.app.drafts==1.0b3'.
warning: no files found matching '*.txt'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Got plone.app.drafts 1.0b3.
The constraint, 2.1.0, is not consistent with the requirement, 'plone.app.tiles>=2.2.0'.
While:
  Installing instance.
Error: Bad constraint 2.1.0 plone.app.tiles>=2.2.0
 !     Push rejected, failed to compile Plone app
```
* Pinning plone.app.tiles=2.2.0 in heroku.cfg does not help.
* Pinning plone.app.tiles=2.1.0 in setup.py does not help.

**Comment by datakurre** [comment]
@pabo3000 Thanks. Could you try if it's fixed now after https://github.com/plone/plone.app.mosaic/commit/680c521fa3196ec54d1972d4f1d77c86bbddc4ed

The heroku deployment used the github master branch instead of release, which has made it broken now, because we have a few unreleased dependencies.

**Comment by pabo3000** [comment]
Sorry, now I have another issue:
```
...
...
...
100  7458  100  7458    0     0   3571      0  0:00:02  0:00:02 --:--:--  3571
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.3.1.zip
Extracting in /tmp/tmpQ6wjFG
Traceback (most recent call last):
  File "bootstrap.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 170, in use_setuptools
  File "<string>", line 122, in _do_download
  File "<string>", line 62, in _build_egg
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 101, in archive_context
  File "<string>", line 85, in __new__
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
 !     Push rejected, failed to compile Plone app
```

Locally I came around it by upgrading setuptools. But how to achieve that on Heroku?

**Comment by datakurre** [comment]
Maybe just wait a day that setuptools gets fixed (it's missing zip-release at PyPI and issue has been made about that).

Pavel Bogdanovic kirjoitti ma syyskuuta 7 12:26:04 2015 GMT+0300:

**Comment by pabo3000** [comment]
setuptools is fixed and the deploy process finished. But it would be boring if it worked.
App does not start up. The traceback is here: http://pastebin.com/XQyQQaMj

If you try out p.a.mosaic locally wit the provided buildout you' ll get the same failure. But If you use buildout.coredev/plips/plip-mosaic.cfg it works.

**Comment by datakurre** [comment]
@pabo3000 Oh, dear. Well, I'll make new releases for the requirements tomorrow, so that Heroku deploy will get the latest version, and ping you on this issue. Thanks for testing and pushing.

**Comment by datakurre** [comment]
Heroku deploy works again and will keep working by relying on released versions only.
