### ISSUE TITLE
Add save layout button for the editor

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#136]
that would allow the currently customized layout as a named layout into portal_resources (or override existing) so that it would be selectable in the layout picker.

**Comment by pbauer** [comment]
:+1:

**Comment by agitator** [comment]
from @@plone.app.standardtiles.field?field=ILayoutAware.content

**Comment by datakurre** [comment]
@pbauer @agitator Yes, that's the way to do it now, until someone makes the integration. Export layout using that view and save it into a new layout using Mosaic control panel (by @vangheem).

**Comment by vangheem** [comment]
fwiw, I'm indifferent if we really want users to be able to save layouts. Too much power! :)

**Comment by datakurre** [comment]
So, then this should be added to the global content layout editor (Mosaic control panel)? A picker to select content item where to fetch the initial layout from?

**Comment by agitator** [comment]
or just an action in the toolbar, protected with admin permissions?
btw. do we have the above link somewhere in the documentation?

**Comment by datakurre** [comment]
@agitator No we don't have yet.

Adding "Import from content" or similar into layout editor is probably the easiest solution for now. The toolbar is getting crowded :)

**Comment by agitator** [comment]
i also don't see it as a top level toolbar icon/action, more of an action within the actions menu where copy/cut ... already are and adding a permission to not allow/show it to every user - would be some kind of admin feature anyway

for the moment i like the idea of standing on the actual content item and "push" it to the "central layout  repository" aka control panel more, than having to go to through the site structure to find and pick that item again.

**Comment by vangheem** [comment]
Maybe layout turns into a dropdown on the mosaic edit bar with "Customize", "Change" and "Save" as options. That'd save us some space.
