### ISSUE TITLE
Disable (or skip) layout selection if only one layout is available 

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#140]

**Comment by datakurre** [comment]
Maybe also when there's a default layout configured for the type? @vangheem? Could a z3c.form default value adapter work here after all?  

agitator kirjoitti to syyskuuta 24 18:58:40 2015 GMT+0300:

**Comment by agitator** [comment]
@vangheem isn't that already done?

**Comment by vangheem** [comment]
yes. this is done.
