### ISSUE TITLE
Spaces are removed from Title field on repeated edit/save

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#142]
steps to reproduce:
- create a layout with a narrow title field and enter a title that is several lines long
- save
- edit 
- save

-> one space is removed somewhere in between

seems to occur around the position where the line break happens

**Comment by datakurre** [comment]
Thanks. This is related to https://github.com/plone/plone.app.mosaic/issues/115

**Comment by vangheem** [comment]
This is fixed.
