### ISSUE TITLE
Tabs in properties stop working if leadimage is added in first draft mode

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#143]
steps to reproduce:
- set layout_view as default_view on page type
- add the leadimage behavior to page type
- add a page and switch to layout mode
- enter title, description, text
- insert the leadimage
- add an image to the leadimage field within the layout
- click properties and switch through tabs

-> it will stop working/switching after the second tab

it occurs only before you save the document and you're still on ++add++Document

**Comment by datakurre** [comment]
Nice catch. Not sure about the reason. Maybe JS console shows the error. Recently, I added some JS code, which was supposed to hide empty tabs. It may have issues.

**Comment by vangheem** [comment]
We no longer show the mosaic editor on the add form.
