### ISSUE TITLE
site and section layout fields are hidden

### ISSUE THREAD

**Issue by vangheem** [plone/plone.app.mosaic#147]
Why are these hidden? https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/widget.py#L180

**Comment by datakurre** [comment]
Too powerful feature and hard to describe for integrators right now. At the last Bristol conference there was an open space about Mosaic and we came to conclusion to make the first release with only content layouts enabled by default (and focus on polishing them).

Those fields (and other code required for site layouts) should be registered with a simple zcml feature flag:

    <meta:provides feature="mosaic-sitelayouts" />

**Comment by datakurre** [comment]
One more reason, why site layouts should be disabled on ZCA level, until they are really needed:

    https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/browser/main_template.py

Site layouts require custom main template view to properly use the configured site layouts also on legacy views (main_template based views like edit, folder_contents, etc). It works OOTB on HTML site layouts with some element with id="content" (and can be made to work also without with a data-attribute, which I should describe in detail later).

**Comment by datakurre** [comment]
@vangheem Does this make sense? Are you already interested in using site layouts?

**Comment by vangheem** [comment]
I'm using it slightly differently but I just thought it was curious to have the fields and implement the ability but then hide it.

I think the scariest part of it is knowing what happens with diazo/site layouts. It would be really confusing for users.

**Comment by datakurre** [comment]
@vangheem If you need just the fields, please, just add some additional condition.

I need to keep the site layouts functionality for myself, but don't want to scare everyone with it.
