### ISSUE TITLE
When I create a content layout with Mosaic Editor, the layout should be saved with Mosaic Grid info

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#15]
which @bloodbare implemented into p.a.blocks to support multiple grid systems

Currently the editor relies on mosaic-grid-row and mosaic-grid-cell etc classes defined in authoring.css.

**Comment by datakurre** [comment]
The easiest implementation would transform data-grid into deco classes when loading the layout into editor and transform deco classes back into data-grid when saving the layout. So, the internal grid in the editor remains deco grid.

**Comment by datakurre** [comment]
@bloodbare Ping. I would have minimal implementation for this, but gridsystem transform in blocks for BS3 and deco are not compatible:

* deco always requires position, because multiple cells with postion-0 will overlap
* BS3 only requries position, if there should be space between cells

For example, if I had:

    "pos": {"x": 1, "width": 6}}}
    "pos": {"x": 7, "width": 6}}}

It looks good with deco, but gs3 adds 6 width of space between

If I had:

    "pos": {"x": 1, "width": 6}}}
    "pos": {"x": 1, "width": 6}}}

BS3 would look good, but deco would show tiles on top of each other.

Any ideas?

If this would, work it would be really cool: Mosaic Editor would create responsible grids for BS3 grids.

**Comment by datakurre** [comment]
I think, I'll take the easy way and introduce state into BS3 grid transform.

**Comment by datakurre** [comment]
https://github.com/plone/plone.app.blocks/commit/4789b2b72847023fb63f0f5bfbc1d88a2c5e0c21

**Comment by datakurre** [comment]
@esteele Ping. When you have time, plone.app.blocks 2.1.1 is waiting for release. Once it's out, Mosaic Editor can create responsive grids for Bootstrap 3 based layouts.

**Comment by datakurre** [comment]
I'd guess, I should include BS3 example layouts in Mosaic for easy demos.

**Comment by tisto** [comment]
@datakurre I granted you the permissions to make a release...

**Comment by datakurre** [comment]
@tisto Thanks. I tried to having maintainer right for that, but it's been too addictive to see this almost working.

**Comment by datakurre** [comment]
@bloodbare FYI about the current implementation:

* I fixed grid transform in p.a.transform to add grid classes instead of replace all classes with them
* I added state for BS3 grid transform so that it adds offset only if the position is larger than the previous position + its width
* Mosaic editor still uses Deco based "Mosaic Grid" internally, but during save, adds ``data-grid``-annotations (only position and width currently, screen size filter annotations require additional UI and other work)
* Mosaic has bodyClass transform, which enables its "Mosaic Grid" also in view mode if no explicit grid is defined in html-tag (this keeps Mosaic Grids working also without BS3 based layouts)
* When page is edited again, Mosaic Editor does not care about data-grid, but still relies on the legacy mosaig-grid-classes.

Yet, this works and is quite cool as seen in Mosaic + BS3 -videos :+)

**Comment by bloodbare** [comment]
Asko you are a machine !!! You are doing a really big work here ! I'm trying to get to it.
My idea is that deco converter or bs3 converter whould need to calculate the position or the width depending on the relative space. There was another bs situation is that can calculate different width depending on the device.

It sounds really great ! Thanks for the effort!
