### ISSUE TITLE
JS errors on console

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.mosaic#150]
I am receiving the attached JS errors on the console with a fresh checkout of plone.app.mosaic/master from 17-10-2015.

![screenshot 2015-10-17 10 26 34](https://cloud.githubusercontent.com/assets/594239/10557538/a25ee978-74b9-11e5-84b1-114ff6072749.png)

**Comment by vangheem** [comment]
This is when you go to the control panel right?

I have seen this--didn't think it was still a problem.

Happens because the custom directory is never created.

**Comment by vangheem** [comment]
Although, I just tested with mosaic plone 5 plip buildout and it is working so maybe something else is going on.

**Comment by tomgross** [comment]
I'm still seeing this with a current clone of master branch 69735b6ab5f77b8169473d44f94bf8b1b7f8f7a9

**Comment by tomgross** [comment]
As a workaround create the sitelayout manually (by copying contentlayout and renaming it):
![mosaic_sitelayout](https://cloud.githubusercontent.com/assets/339384/13143706/0d29dd42-d646-11e5-9380-60e95a24e281.png)

**Comment by vangheem** [comment]
What version of Plone?
