### ISSUE TITLE
Embedding vimeo video breaks layout

### ISSUE THREAD

**Issue by staeff** [plone/plone.app.mosaic#152]
When video content from vimeo is inserted through an embed tile, it breaks the layout in the sense that objects placed on the right hand side of it will overlap with the video.

Steps to reproduce:

* Create embed tile with a vimeo - url (e.g. https://vimeo.com/36897992)
* Create a text tile (just as example, the problem seems to occur with any tile)
* Drag the text tile right of the embed tile to layout them in one line

Here is a screenshot of the result:

![embed-vimeo](https://cloud.githubusercontent.com/assets/464145/10661543/e7fcf38c-78ae-11e5-8a55-abf06cc73f0d.png)

**Comment by vangheem** [comment]
No longer an issue with new grid implementation.
