### ISSUE TITLE
Is there a way to insert a column?

### ISSUE THREAD

**Issue by allcaps** [plone/plone.app.mosaic#153]
I created a two column layout. On desktop size viewport it looks like this:

    ...
    Title 1             Title 2
    Content 1           Content 2

But when I drag the viewport to mobile width, it looks like this:

    ...
    Title 1
    Title 2
    Content 1
    Content 2

Desired, I'd like the titles to stay with their body text:

    ...
    Title 1    
    Content 1
    Title 2
    Content 2

I guess this requires some kind of column tile. Any hints?

**Comment by vangheem** [comment]
Is this a custom that you build with the editor or a layout you wrote with html?

With layout editor, this is possible. It's more about the order that you start building your columns/rows with tiles: https://www.dropbox.com/s/zk4y9ssar6n4q5g/example-columns-mobile.mov?dl=0

Here's what the html looks like:

```
<div class="mosaic-grid-row row">
        <div class="mosaic-grid-cell mosaic-width-half mosaic-position-leftmost col-md-6">
          <div class="movable removable mosaic-tile mosaic-text-tile">
          <div class="mosaic-tile-content">
<h2>Some title</h2><p></p>
          </div>
          </div>
          <div class="movable removable mosaic-tile mosaic-text-tile">
          <div class="mosaic-tile-content">
          <p>foobar</p>
          </div>
          </div>
        </div>
        <div class="mosaic-grid-cell mosaic-width-half mosaic-position-half col-md-6">
          <div class="movable removable mosaic-tile mosaic-text-tile">
          <div class="mosaic-tile-content">
<h2>Another title</h2><p></p>
          </div>
          </div>
          <div class="movable removable mosaic-tile mosaic-text-tile">
          <div class="mosaic-tile-content">
          <p>foobar</p>
          </div>
          </div>
        </div>
      </div>
```

**Comment by vangheem** [comment]
Closing for now. Reopen if there is some problem I don't understand.

**Comment by datakurre** [comment]
This is not the first time, when enforcing rows in the Mosaic editor would have been nice  to have. That's why collective.cover and SeaSprint went with explicit rows. Yet, I really like our (original Deco) editor more. Maybe we figure out later some nice way. 

Nathan Van Gheem kirjoitti ke lokakuuta 28 16:34:19 2015 GMT+0200:

**Comment by allcaps** [comment]
I think I know what I did wrong. I snapped new content to the right side of existing tiles and not to the bottom. I'll add the video: https://www.youtube.com/watch?v=BgwGB09krhc
