### ISSUE TITLE
allow empty embed or image tiles within a (centrally managed) layout

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#156]
I want to prepare a centrally manage layout with placeholders for images and embed. 
afaik i have to add an image/url to be able to place the tile in the layout?

expexted behavior would be that i can add a tile and later add the image/url und if not added, it should not show in the view

**Comment by vangheem** [comment]
I've made my own, very simple, image tile to hit this use-case.

**Comment by tomgross** [comment]
@vangheem Do you have an example of this tile (as a gist)?

**Comment by vangheem** [comment]
https://gist.github.com/vangheem/a98de8dd5c3d00238bdba7509b142536
https://gist.github.com/vangheem/d585773265205ee03569b85d9693698e

or do you need an example of how the layout would work for this?
