### ISSUE TITLE
mosaic layouts shouldn't load tinymce javascripts if not logged in 

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#161]
if mosaic is installed tons of tinymce js are loaded, is that really necessary?

**Comment by vangheem** [comment]
There hasn't been a release of mosaic in a while but the latest builds don't re-include the tinymce js.

**Comment by datakurre** [comment]
Good to know. I've not used CMFPlones' script for bundles so I was not aware of that.

I'll try to catch up early Jan (@vangheem has done a lot of fixes) and make a release.

Nathan Van Gheem kirjoitti ti joulukuuta 22 18:10:44 2015 GMT+0200:

**Comment by agitator** [comment]
using master sources
deleting the mosaic bundles and reinstalling seems to have fixed it

**Comment by vangheem** [comment]
FWIW, when I build with Plone 5, I have to manually add stub entries in resource registry control panel so they do not get included.

**Comment by datakurre** [comment]
@vangheem Do you know, how that issue could be fixed properly? Or is it just a generic issue with using requirejs? (I also stub everything in plone-logged-in-bundle [build.js in repo] when building bundles and simply expect mosaic bundle to be loaded after plone-logged-in-bundle.)

Nathan Van Gheem wrote:

**Comment by vangheem** [comment]
Just a generic issue with requirejs. Need to stub modules you don't want built.
