### ISSUE TITLE
scales from p.a.imagecropping on leadimage get lost on edit of item

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#164]
steps to reproduce:
- create a content item with leadimage
- open cropping editor, select area and save
-> selected crop is used in listing
- edit content item again and save
-> scale without crop is shown in listing
- open cropping editor again
- selected crop area is still correct (you don't have to change anything, just save)
- save cropping area again
-> correct cropped scale is shown again in listing

@frisi any idea what could be wrong?

**Comment by datakurre** [comment]
Does this happen only with Mosaic installed? Or what's the relation to Mosaic?

agitator wrote:

**Comment by agitator** [comment]
weird... after being able to reproduce it once, it seems to work now and not reproduceable anymore
closed for now, will check and reopen if it's an issue again

**Comment by hvelarde** [comment]
@agitator I think we need a build on the plone.app.imagecropping matrix testing with Mosaic installed

**Comment by agitator** [comment]
@hvelarde p.a.imagecropping would need some love for plone5 anyway, but basically works

**Comment by frisi** [comment]
@agitator sorry for the delay.
i did not look into p.a.mosaic what could be wrong but i definitely have the same problems (cropped images get lost when editing a document) using p.a.imagecropping with raptus.article.teaser. 
the interesting thing: it is not 100% reproducable.

cropping information is still there, but editors need to got to the cropping view and re-save all scales they previously defined crops for.
to automate this process i created a utiltiy view in this branch: https://github.com/collective/plone.app.imagecropping/commits/recreate-crops
it's no solution for the root of the problem, but might be a useful workaround for you.

**Comment by agitator** [comment]
@frisi good, then i'm not going crazy... ;-)
