### ISSUE TITLE
Views not configured when adding DX type with layout behavior TTW

### ISSUE THREAD

**Issue by thet** [plone/plone.app.mosaic#169]
When adding a Dexterity type TTW via the ``@@dexterity-types`` control panel and adding the layout and drafting behaviors, the ``default_view`` and ``view_methods`` FTI attributes should be updated to contain the ``layout_view``.
Aren't.

**Comment by datakurre** [comment]
Is there any hook where to do that?

I remember this being the issue why the layout view was initially just @@view, but that coul have cause other issues in the long run.

**Comment by Martronic-SA** [comment]
There's missing a (DexterityFTI, behavior) adapter that would perform the changes on the DexterityFTI when the behavior is added to it.
I think that plone.app.dexterity.browser.behavior.BehaviorConfigurationAdapter should retrieve and call the (DexterityFTI, behavior) adapter on setattr and getattr.

What do you think?
