### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.mosaic#172]
Previous release 1.0b3 was in September. I see lots of changes since then, which deserve a new release.

Also, I tried upgrading a site with that version from Plone 5.0 to 5.0.3-pending, and the edit form for mosaic was broken, giving `KeyError: 'pattern_options'`. When I try a checkout from master, this error is gone.

**Comment by datakurre** [comment]
Should it be 1.0 already? It's not completely without issues, but it's already used in production.

**Comment by mauritsvanrees** [comment]
+1 on numbering it 1.0. The current beta release is half a year old, that's long enough to consider it stable.

**Comment by datakurre** [comment]
:+1: I wait for @vangheem's current work saving layouts directly from the layout editor. (In 1.0b3 there's no way to save layouts without understanding mosaic html.)

**Comment by datakurre** [comment]
1.0rc1 released https://pypi.python.org/pypi/plone.app.mosaic

Would you agree with the following Mosaic roadmap? /cc @vangheem @esteele 

* 1.0rcX => 1.0 when possible critical or packaging issues are no longer found
* then we archive/branch master as 1.x and move development version to 2.0.dev0
* 1.x will remain Plone 4.3.x compatible (I may backport patches to it when I need to)
* 2.x will be Plone 5 only, my old layout-menu / view alias configuration can be removed 
* 2.x will be PLIP'd to be bundled with Plone 5.2

Same major versioning policy for plone.app.standardtiles and other dependencies when Plone 4 support is being dropped.

**Comment by vangheem** [comment]
+1 Looks good @datakurre

**Comment by agitator** [comment]
nice!

**Comment by mauritsvanrees** [comment]
Thanks for the release.
The roadmap looks good.

+1 for a soonish 1.0 final.

As for possible critical issues, I have found and fixed one problem when trying 1.0rc1: b071a168307776b0c3b24483d807511eb475b2fc
This was while editing a page on a 5.0 site that I had just upgraded to 5.0.4.

**Comment by datakurre** [comment]
@mauritsvanrees Thanks, I do rc2 with that later today. The main point in 1.0 is to get to proper semver release cycle, so no better to start already in rc :)
