### ISSUE TITLE
Textfields in custom layouts

### ISSUE THREAD

**Issue by mr-rob** [plone/plone.app.mosaic#176]
When using a custom template which has two or more mosaic-text-tiles the content of the text tiles won't get saved. 

Steps to reproduce the behaviour:
•	Create custom layout with two elements of the type mosaic-text-tile
•	Create New Site and set mosaic-layout
•	Set Layout to the newly created custom layout
•	Edit text of the mosaic-text-tile and hit save
•	Changed text isn’t saved

Workaround:
When editing the site add a new mosaic-text-tile (Insert->Structure->Text). At this point a POST-request will be sent (@@z3cform_validate_field). The field can be removed again. And changes to the other fields will be saved.

Test-Layout: https://gist.github.com/mr-rob/586d5f8745b486d36513

**Comment by vangheem** [comment]
You can use rawhtml tile instead in your custom templates which store the html data persistently and not in the layout. Look in plone.app.standardtiles for details about the tile.
