### ISSUE TITLE
JS Error when i define own Layouts

### ISSUE THREAD

**Issue by 1letter** [plone/plone.app.mosaic#184]
I would like to offer a predefined Document Layout. I have registered the Layout in my own Theme Package, all is fine and work. The Layout contain three Tiles of Type: "ExistingContentTile". I have define the Structure like the Examples in [Plone5 Contentlayout](https://github.com/plone/plone.app.mosaic/tree/master/src/plone/app/mosaic/layouts/plone-5/content)

```html
<div class="mosaic-grid-row">
    <div class="mosaic-grid-cell mosaic-width-full mosaic-position-leftmost">
      <div class="movable removable mosaic-tile mosaic-IExistingContentTile-content_uid-tile">
        <div class="mosaic-tile-content">
          <div data-tile="./@@plone.app.standardtiles.field?field=IExistingContentTile-content_uid"></div>
        </div>
      </div>
    </div>
</div>
```
I get the following JS Errors when i use the Layout:
- `patterns.pat-mosaic: Could not load tile config for tile type: IExistingContentTile-content_uid`
- `Uncaught TypeError: Cannot read property 'tile_type' of undefined`

I think my 'data-tile' Attribute `./@@plone.app.standardtiles.field?field=IExistingContentTile-content_uid`  or the class `mosaic-IExistingContentTile-content_uid-tile` is wrong, but I don't know really. Is there a documentation anywhere for creating Layouts with the right Attributes? The Examples uses the Interfaces and Field Names, i think that is so, but i know it really.

**Comment by vangheem** [comment]
The field tile is for fields on content objects, not fields in tiles.

Here is a general guide to getting/using tiles in your layouts...

First off, make sure zcml is there:
```
  <plone:tile
    name="my.tile"
    title="My Tile"
    class=".path.to.Tile"
    schema=".path.to.ISchema"
    for="*"
    add_permission="cmf.ModifyPortalContent"
    permission="zope.Public"
    template="path/to/template.pt"
    />
```

Then, unfortunately, there is additional mosaic registration code you need. Something like this will need to be in your registry.xml:
```
<record name="plone.app.tiles">
    <value purge="false">
      <element>my.tile</element>
   </value>
</record>

<records prefix="plone.app.mosaic.app_tiles.my_tile"
           interface="plone.app.mosaic.interfaces.ITile">
    <value key="name">my.tile</value>
    <value key="label">My Tile</value>
    <value key="category">advanced</value>
    <value key="tile_type">app</value>
    <value key="default_value"></value>
    <value key="read_only">false</value>
    <value key="settings">true</value>
    <value key="favorite">false</value>
    <value key="rich_text">false</value>
    <value key="weight">20</value>
  </records>
```

Then, in your layout, it'd be defined like:
```
<div class="mosaic-grid-row">
    <div class="mosaic-grid-cell mosaic-width-full mosaic-position-leftmost">
      <div class="movable removable mosaic-tile
                  mosaic-my.tile-tile">
        <div class="mosaic-tile-content">
          <div data-tile="./@@my.tile/1"></div>
        </div>
      </div>
    </div>
  </div>
```

In specifying the data-tile attribute, notice how it's done: `data-tile="./@@my.tile/1"`. The `/1` in the url specifies the unique id of the tile. You can share this unique id across different layouts and the data will persist properly(if that makes sense for your use-case). Or this can just be a random number.

One other thing, you can create custom layouts and save them. Then you can inspect your custom layouts and see how it generates the layout with your tile config.

**Comment by 1letter** [comment]
Thanks for Explanation
