### ISSUE TITLE
Cannot remove a text tile saved as movable_removable_mosaic-tile_mosaic-text-tile_mosaic-helper-tile-new_mosaic-drag-cancel

### ISSUE THREAD

**Issue by acsr** [plone/plone.app.mosaic#187]
## Issue

I have some trouble to even catch a text tile that losts all its content using plain html editing. We activated the feature to insert classes and ids to style certain content in tiles via CSS. 

After saving the page this "ghost" tile is visible at the end of the page View containing the default "Lorep Ipsum.." placeholder text.

After entering Edit mode the content is attached to the mouse pointer with a serious offset of 500px very low and difficult to discover.

This behaviour is persistent over a copy paste of the page or opening over a different browser or URL.

## Steps to reproduce

No idea how, but we managed to save a mosaic layout page during work on the front page for the new Plone Conference using mosaic. 

We currently use Plone 5.0.2 and plone.app.mosaic 1.0b3 (more detailed versions on demand)
We register a profile to activate HTML edit and a custom Slider provided by @vangheem .

The plone.app.mosaic is customised via the profile/registry.xml in this package: https://github.com/jazkarta/ploneconf2016.policy/blob/master/ploneconf2016/policy/profiles/default/registry.xml

## Broken Content Example

Full snipped of the saved tile catched via External Edit:

 ```
exclude_from_nav: True
title: Explore next Generation Digital Experiences
description: =?utf-8?q?Meet_Plone_5_=C2=B7_International_Professional_Communities_?=
 =?utf-8?q?=C2=B7_New_to_Plone_Come_Together_=C2=B7_Joined_Trainings_?=
 =?utf-8?q?=C2=B7_Sprints?=
subjects: 
language: en-us
effective: 2016-04-17T17:38:00
expires: 
creators: admin||acsr
contributors: 
rights: 
content: =?utf-8?q?=3C!DOCTYPE_html_PUBLIC_=22-//W3C//DTD_XHTML_1=2E0_Transitional?=
 =?utf-8?q?//EN=22_=22http=3A//www=2Ew3=2Eorg/TR/xhtml1/DTD/xhtml1-transit?=
 =?utf-8?q?ional=2Edtd=22=3E=0D=0A=3Chtml_xmlns=3D=22http=3A//www=2Ew3=2Eo?=
 =?utf-8?q?rg/1999/xhtml=22_xml=3Alang=3D=22en=22_lang=3D=22en=22_data-lay?=
 =?utf-8?q?out=3D=22=2E/=40=40page-site-layout=22=3E=0D=0A__=3Cbody=3E=0D=0A?=
 =?utf-8?q?=0D=0A____=3Cdiv_data-panel=3D=22content=22=3E=0D=0A______=3Cdiv_c?=
 =?utf-8?q?lass=3D=22mosaic-grid-row=22=0D=0A___________data-grid=3D=27=7B?=
 =?utf-8?q?=22type=22=3A_=22row=22=7D=27=3E=0D=0A________=3Cdiv_class=3D?=
 =?utf-8?q?=22mosaic-grid-cell_mosaic-width-half_mosaic-position-leftmost?=

... shortened

 =?utf-8?q?le-content=22=3E=0D=0A=3Ch3=3EMedia_Partners=3C/h3=3E=0D=0A____?=
 =?utf-8?q?______=3C/div=3E=0D=0A__________=3C/div=3E=0D=0A__________=3Cdi?=
 =?utf-8?q?v_class=3D=22movable_removable_mosaic-tile_mosaic-text-tile_mos?=
 =?utf-8?q?aic-helper-tile-new_mosaic-drag-cancel=22=3E=0D=0A__________=3C?=
 =?utf-8?q?div_class=3D=22mosaic-tile-content=22=3E=0D=0A=3Cp=3ELorem_ipsu?=
 =?utf-8?q?m_dolor_sit_amet=2C_consectetuer_adipiscing_elit=2E_Sed_posuere?=
 =?utf-8?q?_interdum_sem=2E_Quisque_ligula_eros_ullamcorper_quis=2C_lacini?=
 =?utf-8?q?a_quis_facilisis_sed_sapien=2E_Mauris_varius_diam_vitae_arcu=2E?=
 =?utf-8?q?_Sed_arcu_lectus_auctor_vitae=2C_consectetuer_et_venenatis_eget?=
 =?utf-8?q?_velit=2E_Sed_augue_orci=2C_lacinia_eu_tincidunt_et_eleifend_ne?=
 =?utf-8?q?c_lacus=2E=3C/p=3E=3Cp=3EDonec_ultricies_nisl_ut_felis=2C_suspe?=
 =?utf-8?q?ndisse_potenti=2E_Lorem_ipsum_ligula_ut_hendrerit_mollis=2C_ips?=
 =?utf-8?q?um_erat_vehicula_risus=2C_eu_suscipit_sem_libero_nec_erat=2E_Al?=
 =?utf-8?q?iquam_erat_volutpat=2E_Sed_congue_augue_vitae_neque=2E_Nulla_co?=
 =?utf-8?q?nsectetuer_porttitor_pede=2E_Fusce_purus_morbi_tortor_magna_con?=
 =?utf-8?q?dimentum_vel=2C_placerat_id_blandit_sit_amet_tortor=2E=3C/p=3E?=
 =?utf-8?q?=0D=0A__________=3C/div=3E=0D=0A__________=3C/div=3E=0D=0A_____?=
 =?utf-8?q?___=3C/div=3E=0D=0A______=3C/div=3E=0D=0A____=3C/div=3E=0D=0A__?=
 =?utf-8?q?=3C/body=3E=0D=0A=3C/html=3E?=
contentLayout: 
pageSiteLayout: 
sectionSiteLayout: 
id: landing-page
changeNote: 
table_of_contents: False
relatedItems: 
allow_discussion: 
MIME-Version: 1.0
Content-Type: text/html; charset="utf-8"
Portal-Type: Document

<div class="three-col col-2 col-mid" style="vertical-align: text-top; text-align: center;"><img class="image-inline" title="Feel it" src="../resolveuid/358b224626664e7eb03b5873b7989df9/@@images/image/preview" alt="" data-linktype="image" data-scale="preview" data-val="358b224626664e7eb03b5873b7989df9" /></div>
<h3 style="text-align: center;"><strong>Feel it</strong></h3>
<h2 style="text-align: center;"><em>Feel Plone's Power, Flexibility ans Usability to Create Experiences</em></h2>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat</p>

```

## Solution Suggestions

1. Filter for non placed tile content on save and fix it to either to be deleted or sanitized content to be deleted later.
2. Add a way to select every tile even in unspecific state to delete it when its broken. (use a hotkey to jump from tile to tile to select them one after the other to finally remove a broken tile.

**Comment by acsr** [comment]
Question: How can I fix this as an author or integrator TTW without recreating the content? ZMI is OK.

**Comment by datakurre** [comment]
Thanks. This should be fixable (if not already fixed) in code where the editor serialises the layout.

Workaround
1. Select old style view from display menu
2. Edit element and copy content from Layout / Content layout field into your favourite html editor.
3. Remove the tile with mosaic-new... class (also just removing that class should help)
4. Copy layout data back to Plone and save the content

**Comment by acsr** [comment]
@datakurre Thanks back. Workaround was easy as a snap. Did not know that the content was that easy accessible in the UI. Very important when using in production. Need to check that with latest version later. 

Step to reproduce by adding a similar issue to mosaic content for testing:
- In mosaic edit mode, add a text tile and keep the default text.
- place it and save the document. (The erratic steps are still not reproducable until I figur them out)
- disable the mosaic view in display menu
- enter edit mode and go to the layout tab at the top
- copy the text of content field into your favorite text editor
- add the classes "mosaic-helper-tile-new" and "mosaic-drag-cancel" into the main <div> of the tile behind:
`class="movable_removable mosaic-tile mosaic-text-tile"` seperated by spaces!
- copy back the text and save.
- reenable the mosaic view.

Test:
When you open the page to edit. Check if the object is filtered correcly on save.
