### ISSUE TITLE
'X' on tile modal breaks javascript

### ISSUE THREAD

**Issue by shadowmint** [plone/plone.app.mosaic#189]
Steps to repeat:

- Add a tile 
- Save
- Edit the page
- Edit the tile
- Instead of clicking on 'cancel' click on 'X' in the top right corner of the modal.

The model will close.

Attempt to edit the tile again; the console reports:

```
plone-mosaic.js:269 patterns.pat-mosaic: Could not load tile config for tile type: editedt.output @ plone-mosaic.js:269a.log @ plone-mosaic.js:269a.error @ plone-mosaic.js:269m.getConfig @ plone-mosaic.js:269(anonymous function) @ plone-mosaic.js:269m.event.dispatch @ jquery.min.js:4b.dispatch @ plone-compiled.min.js:4r.handle @ jquery.min.js:4
plone-mosaic.js:269 Uncaught TypeError: Cannot read property 'tile_type' of undefined(anonymous function) @ plone-mosaic.js:269m.event.dispatch @ jquery.min.js:4b.dispatch @ plone-compiled.min.js:4r.handle @ jquery.min.js:4
```

Other tiles on the page are not affected.

Workaround:

- Select a different tile on the page
- Edit
- Hit cancel

You can now edit the first tile again without a problem.

This issue occurs only when you use the 'X' in the modal title bar.

Mosaic version: 1.0

**Comment by datakurre** [comment]
Thanks for the report.

**Comment by vangheem** [comment]
Can no longer reproduce in master. I believe this was fixed a long time ago.
