### ISSUE TITLE
Unexpected clustering of rows as one div when applying row styles

### ISSUE THREAD

**Issue by acsr** [plone/plone.app.mosaic#191]
I have multiple rows in a mosaic layout (mosaic 1.0 in Plone 5.0.4)
When I apply a row style (the available default is "Dark Background"), the style "clusters" multiple adjacent rows into one div with the selected class. This is done up and down the row order independent of the selected row in the "magnetic family".

There is some business logic that does the magic. 
I cannot figure out a workaround except manually editing the tiles in the source code.

not sure if it is a bug or a feature.

## Purpose , Example to reproduce

We need to tighten / widen whole rows for the Ploneconf 2016 website where we use mosaic for the frontpage. Adding additional row styles to the menu worked fine. But to reach the intended design and have it editable, we need to style some adjacent rows different that are clustered now.

### What type sequence is clustered?

We have a sequence of 
- a Media Image tile (using a custom image resolution "hdbanner" of 1980x1980 pixels set in the image controlpanel)
- the Field Title tile
- the Field Summary tile

**Remark**: 
It is currently not possible to replace the Image tile with a text tile containing the wide image, because [the text tile only accepts the default Plone image sizes](plone/plone.app.mosaic#192).

## Question

Were can I set the wrench to fix this as a workaround?

## Solution Suggestions

- Add a structure object "divider" that makes sure the adjacent rows are never clustered

or
- Add a structure object "joiner"  that makes sure the adjacent rows are always clustered

or (deluxe)
- show a "chain/unchain" toggle icon making clustering of styles a snap

**Comment by datakurre** [comment]
Thanks for the report. There may be a duplicate for this somewhere.

Mosaic editor does implicitly manage rows for grid and that does not always play as expected with the row styles. I'd like to avoid explicit row management as long as possible, but probably some kind of explicit row splitter could be handy. Or maybe the editor could recognise rows with styles and not merge those automatically until styles are removed (or matching).

**Comment by vangheem** [comment]
This is now solved with the "outline mode"(hold alt key) or by using the row splitting technique of adding a tile next to the tile you do not want to group together, then deleting immediately. This forces the new row to be created.
