### ISSUE TITLE
Structure Text tile image placement does not list custom image sizes from controlpanel

### ISSUE THREAD

**Issue by acsr** [plone/plone.app.mosaic#192]
We created a custom image size TTW in the image controlpanel with id hdbanner and 1989x1980 size.

You can add the custom size in a Media Image tile as selectable size.

If you try to add an image to the structure text tile using the editor icon, the custom size is not listed in the selectable sizes.

We use .plone.appmosaic 1.0 in a Plone 5.0.4 site.

We added/registered custom row styles (should have no effect) and have a custom slider tile in the https://github.com/jazkarta/ploneconf2016.policy package.

**Comment by martior** [comment]
Does the custom scale work for you on a normal page? I can't get that to work either, so I looked at the tinymce pattern code.

To me it looks like the scales are hardcoded, and it doesn't call back to the server for a list of scales. https://github.com/plone/mockup/blob/master/mockup/patterns/tinymce/pattern.js#L165

**Comment by datakurre** [comment]
Thanks for the report. I thought we are using the portal TinyMCE configuration. But because the default sizes are there, it could also be a caching issue.

**Comment by vangheem** [comment]
This is fixed in 5.1 and here is the PR for 5.0: https://github.com/plone/Products.CMFPlone/pull/1752

This isn't specific to mosaic.
