### ISSUE TITLE
Layout editor does not open anymore.

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.mosaic#194]
I'am investigating...

**Comment by datakurre** [comment]
@jensens I was seeing the same. Checking, if the widget is rendered at all.

**Comment by datakurre** [comment]
I think, the widget does not fire, so something breaks its registration.

**Comment by datakurre** [comment]
I'll add a failing test soon. Widget is registered, but something overrides it in z3c.form context.

**Comment by datakurre** [comment]
Oh, sorry. It's simply hidden.

**Comment by datakurre** [comment]
@jensens Ok. The issue is caused by content field of layout behavior being omitted by

https://github.com/plone/plone.app.blocks/commit/f9c283d33b8c1c4d9d315863ffb6756f1c662e80

Because it's omitted. It's not rendered and there's no widget.

**Comment by datakurre** [comment]
@jensens Apparently ``plone.app.blocks.interfaces.IOmittedField`` was not meant to really omit field in sense of plone.autoform omit-directive, but rather provide a way to hide them in custom UI. That's probably Deco old and I'm not sure if we have used it in Mosaic.

Major difference in Deco and Mosaic is that Mosaic provided editor as a field widget (pattern) and therefore required field to be rendered, which was not the case in Deco.

**Comment by datakurre** [comment]
So simply removing omitted from layout aware behavior fields would fix this.

**Comment by jensens** [comment]
So the idea of omitted is to actually disable site layout selection? 
a) omitted is then a bad name for it
b) why disable site layout selection? imo a site manager should be able to do so, an editor not.

**Comment by datakurre** [comment]
@jensens I believe it was related to Deco UI implementation. Legacy. Permissions would be the right way. Maybe DX, autoform, etc were not as mature as now 5 year ago.

**Comment by datakurre** [comment]
@jensens It was used to omit layout fields from field tiles https://github.com/plone/plone.app.deco/blob/master/plone/app/deco/utils.py#L62

**Comment by datakurre** [comment]
@jensens And that's still the case in Mosaic https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/utils.py

**Comment by datakurre** [comment]
@jensens I'm okay for excplicitly omitting layoutbehavior fields in Mosaic code and then rely on registry configuration for other possibly omitted behavior fields (there's already a configuration for that).

**Comment by datakurre** [comment]
So, that should still be fixed:

![mosaic-editor-select-field-text-tile](https://cloud.githubusercontent.com/assets/160447/14884939/17faf3c2-0d51-11e6-860a-002c3849e4d5.png)

**Comment by datakurre** [comment]
I'll open a new issue.

**Comment by jensens** [comment]
we may provide an own form hint, thats quite easy.

**Comment by datakurre** [comment]
@jensens I'm :+1: for any fix :-) https://github.com/plone/plone.app.mosaic/issues/195
