### ISSUE TITLE
Mosaic pages and historyview

### ISSUE THREAD

**Issue by martior** [plone/plone.app.mosaic#198]
Looking at historyview on folders with a mosaic layout, changes to the layout does not seem to create new versions. Am I looking at the wrong place here?

**Comment by datakurre** [comment]
Strange. There should not be anything preventing versioning from happening. Yet, it's good to know, that tiles with blob may have other issues it it: https://github.com/plone/plone.app.mosaic/issues/80

**Comment by hvelarde** [comment]
@martior have you enabled versioning on your content type? that doesn't happens automatically:

https://community.plone.org/t/dexterity-versioning-does-not-appear-to-work/1563/2?u=hvelarde

**Comment by martior** [comment]
@hveiarde it was a normal folder, so I just assumed. I will have to check.

**Comment by datakurre** [comment]
@martior Folder's are not versioned by default, because versioning just title and description (the case without Mosaic) does not make much sense, so that's probably the issue then.

**Comment by datakurre** [comment]
I assume versioning was not enabled (because it's not enabled for the default Folder type).
