### ISSUE TITLE
global statusmessage invalid html

### ISSUE THREAD

**Issue by thet** [plone/plone.app.mosaic#199]
Please note the data-slots in the aside tag:
```
    <aside id="global_statusmessage" data-slots="> global_statusmessage">
      <div data-tile="./@@plone.app.standardtiles.global_statusmessage"></div>
    </aside>
```

Not sure, what the intention was - but this produces invalid html output. This is the case for almost all site layouts in plone.app.mosaic.

**Comment by datakurre** [comment]
@thet Thanks for noticing that. Obviously, ">" in data-slots should be replaced with something less offending. I wonder, why LXML didn't complain about those in the beginning... Yet, even now, those should not exist in the final output.

About data-slots. They are optional annotation to provide backwards compatibility ("metal:define-slot":s) from HTML site layouts to TAL template based views. They make it possible that HTML site layout can be used to render legacy TAL based views (like sharing, content listing, etc...).

https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/browser/main_template.py#L39
