### ISSUE TITLE
Tiles transform should avoid subrequest whenever possible

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#20]
for better performance.

See also: https://gist.github.com/vangheem/2c625d89c33c1010662c

This should be implemented in p.a.blocks. Probably creating a new resolveTileUrl into its utils.

Important: We don't need to try to fix the whole request.form. We only need to set the tile data as JSON encoded string into self.request.form['_tiledata'] (see plone.tiles default data manager implementation).

**Comment by vangheem** [comment]
Closing this. We aren't going to do it unless we start to notice performance issues. For now, the branch implementing it is here: https://github.com/plone/plone.app.blocks/tree/no-subrequest-tile-render
