### ISSUE TITLE
existing content tile does not show any items in news collection

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.app.mosaic#202]
With Plone 5.0.4 and Mosaic 1.0, if I add an existing content tile and try to select the /news/aggregator collection the tile renders showing "no items in folder" instead of the 2 news items that are actually there (and published, and they show correctly if I go to the site's News folder)

**Comment by tkimnguyen** [comment]
Here the right tile is an existing content tile; it thinks there are no items to show, but the left tile is a content listing tile, and it correctly shows the site's published news items.

![image](https://cloud.githubusercontent.com/assets/815418/15614209/1a3eb9b2-23fd-11e6-8ad6-db1fc7807a78.png)

**Comment by vangheem** [comment]
probably because it's using a relative path query and since you're now rendering that in a different location that relative path doesn't work--might be a tough bug to fix.

**Comment by tkimnguyen** [comment]
Ah dang you're right, it was using a relative path query (./..)... ok, that's understandable and easy to fix in the collection. How do we help users avoid this problem?

**Comment by tkimnguyen** [comment]
Hm, ok I was wrong: the collection does not use a relative path criterion:

![screen shot 2016-05-27 at may 27 12 51 57 pm](https://cloud.githubusercontent.com/assets/815418/15616521/f3643a12-2409-11e6-906f-2305d1c4245c.jpg)

**Comment by datakurre** [comment]
Existing content works by rendering the content core macro from the target content's view. It could be possible that collection's macro requires some variables we don't define yet.

**Comment by vangheem** [comment]
I have confirmed this is a problem and am investigating.

**Comment by vangheem** [comment]
Fix is here: https://github.com/plone/plone.app.standardtiles/pull/45

**Comment by tkimnguyen** [comment]
Thanks :)
