### ISSUE TITLE
add title field to content listing tile

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.app.mosaic#203]
The content listing tile works great, but it lacks a title field

**Comment by vangheem** [comment]
Add a rich text tile and make your own title?

**Comment by tkimnguyen** [comment]
Yeah, easy workaround is to add another rich text tile above. And yes to your second question (having the tile configuration include a new title field).

**Comment by vangheem** [comment]
We're going to keep standard tile implementation simple right now. If you want a more customized version of existing content, we advise you to implement your own tiles.

The suggested way to hit your use-case is to use rich text above the tile.
