### ISSUE TITLE
Toolbar has broken styles

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#220]
![mosaic-editor-select-field-text-tile 1](https://cloud.githubusercontent.com/assets/160447/16267108/c0610bd6-3890-11e6-9aca-d46ba1946d42.png)

After https://github.com/plone/plone.app.mosaic/pull/219

Anything usable OOTB would be nice :)

/cc @jensens

**Comment by jensens** [comment]
well, for Plone 5 this should go into the left toolbar, replacing the options usually there.

**Comment by vangheem** [comment]
My bad, sorry, I guess I didn't realize how much of bootstrap mosaic uses since in my project we have our own toolbar styles.

Seems to me like we shouldn't include all of bootstrap though still.

Want me to revert https://github.com/plone/plone.app.mosaic/pull/219 ?

**Comment by datakurre** [comment]
Merging Mosaic toolbar into Plone toolbar may not be trivial and until then some default UI should be provided. I don't have strong opinions on UI, but it should not look broken.

About requiring the full bootstrap. That was my bad. I thought that with (reference) LESS only includes the used mixins.

**Comment by datakurre** [comment]
Btw, did you confirm that not removing bootstrap includes really reduced the final CSS? If it was not significant, maybe then the pull could be reverted until we have alternative UI.

**Comment by agitator** [comment]
@vangheem what speaks against reverting?

or what would be a workaround?

**Comment by agitator** [comment]
column styles for "view" are missing...

**Comment by agitator** [comment]
reverted the changes

double dropdowns still exist, where should those styles come from or where should i put them?

**Comment by vangheem** [comment]
select2 styes? Those are select2 widgets and should have something like this applied to them:

![screen shot 2016-08-03 at 2 33 43 pm](https://cloud.githubusercontent.com/assets/524413/17379299/5cd3c33e-5987-11e6-9ac6-dce46dfdca41.png)

**Comment by vangheem** [comment]
@agitator or anyone else. Can you try https://github.com/plone/plone.app.mosaic/pull/255 and see if that fixes the duplicate button issue.
