### ISSUE TITLE
TinyMCE toolbar hidden on tiles below original viewport 

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#221]
* longer than viewport page with tiles below the start viewport
* scroll down
* select tile
* TinyMCE toolbar don't appear

Commenting out the "sticky" behavior seem to fix this somewhat. Need to look into that.

https://github.com/plone/plone.app.mosaic/commit/41c932fba3d0b4f74374ae32a8a1d46ec79589e0

**Comment by vangheem** [comment]
Should be fixed with: https://github.com/plone/plone.app.mosaic/commit/5183c94149b781629a585612a5f69bb3959f7795

reopen if still a problem.
