### ISSUE TITLE
Can't install on Plone 5.0.4

### ISSUE THREAD

**Issue by codecleric** [plone/plone.app.mosaic#222]
Hello,

This is a fresh plone install, and the buildout.cfg has the following section:

`[instance]
 eggs =
      plone.app.mosaic`

When I run buildout, I get the following error:

> Error: The requirement ('plone.app.drafts>=1.0') is not allowed by your [versions] constraint (1.0b3)

If I add plone.app.drafts>=1.0b3 to the eggs section, plone.app.drafts does install, but mosaic won't. I've tried this on Ubuntu and Windows 10, with the same effect.

**Comment by tomgross** [comment]
Hi @codecleric did you pin the versions as documented?

> plone.tiles >= 1.5.2
> plone.app.tiles >= 2.2.1
> plone.app.standardtiles = 1.0
> plone.app.blocks >= 3.1.0
> plone.app.drafts >= 1.0
> plone.app.widgets >= 1.8.0

**Comment by codecleric** [comment]
Hi @tomgross - bear with me as I'm new to plone (although I wrote some extensive apps in Zope 2 back in the day). It the documentation (The readme for this project), I see:

> Plone Mosaic is installed by building a Plone site with package plone.app.mosaic and activating its Plone Mosaic add-on. The package has following dependencies:

> plone.tiles >= 1.5.2
> plone.app.tiles >= 2.2.1
> plone.app.standardtiles = 1.0
> plone.app.blocks >= 3.1.0
> plone.app.drafts >= 1.0
> plone.app.widgets >= 1.8.0

Which I took for informational, and assumed pip would take care of that in the background. Are these lines supposed to be put in the [versions] sections of the config?

Thanks for your response!

**Comment by vangheem** [comment]
I think I've seen this will buildout from a git clone. Are you installing from a release or cloning master?

**Comment by codecleric** [comment]
I am using the universal installer downloaded from the site.

**Comment by vangheem** [comment]
@codecleric can you try this in your versions section?

```
plone.app.drafts=1.0
plone.app.tiles=2.2.1
plone.app.blocks=3.1.0
plone.app.standardtiles=1.0
plone.tiles=1.6.0
plone.app.tiles=2.2.1
```

The reason this is necessary is because plone provides default versions of these packages that are incompatible with the latest version of plone.app.mosaic.
