### ISSUE TITLE
Display proper error message, if a tile can not be found

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#224]
If Mosaic does not find a tile (you see it in the 404 of Firebug) it shows an endless spinner and never returns. Instead a verbose message ("Tile XY could not be found in registry. See _[link_to_doc]_ on how to register tiles") should be displayed.

**Comment by vangheem** [comment]
https://github.com/plone/plone.app.mosaic/pull/263 should fix this.
