### ISSUE TITLE
Handling of mosaic on default pages is broken

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#225]
The handling of mosaic page composition is inconsistent on default pages.

Steps to reproduce:
1) Create a folder /a
2) Create a page inside the folder /page
3) Make page default page of folder
4) Make page a mosaic page
5a) Edit page /Plone/a/page/edit works!
5b) **Edit page /Plone/a/edit has inconstencies. (e.g. some tiles can't be added, page can not be saved, etc.) ** 

I guess the URL of some AJAX calls hit the folder and not the page.

**Comment by vangheem** [comment]
I'm not sure I understand this.

/Plone/a/edit should be editing the folder, not the mosaic page/layout. If you set `/Plone/a/page` as the default page for `/Plone/a`, then when you click "edit" it should always go to `/Plone/a/page/edit`.

This the current behavior.

I'm going to close this ticket.

If I misunderstood, please reopen.
