### ISSUE TITLE
customized layouts should not get an extra .row on .mosaic-grid-row

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#229]
instead of "mosaic-grid-row" customized layouts get "mosaic-grid-row row" as row class, 
causing the layout to wider than it should be

where does this come from?
or is it missing an extra style for view?

**Comment by vangheem** [comment]
"row" is the configured grid framework implementation. Default bootstrap 3.

**Comment by vangheem** [comment]
mosaic-grid-row should be minimal and sometimes I've found I've had to tweak the grid row styles in order to make both match.

**Comment by agitator** [comment]
and what about column styles?
i don't see any any bootstrap specific classes on the columns
class="mosaic-grid-cell mosaic-position-leftmost mosaic-width-two-thirds cell position-0 width-8"

is there another transform that should happen?

**Comment by vangheem** [comment]
Okay, I think the default there is using deco by default then.

See the default_grid_system registry setting.

This should be changed to "bs3" for Plone 5.

I'm still closing this ticket. This is operating as expected. Perhaps create a new ticket describing that the default grid system for plone 5 does not work as "deco" and should probably be set to "bs3". Would be nice for a control panel for this as well?

**Comment by agitator** [comment]
thanx, thought I'm going nuts...

**Comment by datakurre** [comment]
Agreed that BS3 should be the default now.

deco-like "mosaic-grid"-styles are only for the editor

**Comment by agitator** [comment]
not an issue with bs3 as default grid

new issue for default grid system https://github.com/plone/plone.app.mosaic/issues/230
