### ISSUE TITLE
Remove pluggable grid framework

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#231]
- use bs3 or bs4 grid?
- re-use existing mosaic grid class names

i guess this will have consequences for the editor itself, 
but there should be no visual difference for the user

maybe it's enough to strip down deco styling to the absolute minimum, 
or put minimum required styles into an edit-grid stylesheet

**Comment by datakurre** [comment]
The challenge here is that Mosaic is designed to be grid system agnostic and the editor has no idea of the target grid system. The markup created by Mosaic is transformed into the final grid specific syntax by the grid transform in plone.app.blocks.

So, stripping down deco styling to the absolute minimum and/or making it possible to "theme" it with the final grid would be nice.

**Comment by vangheem** [comment]
I think we should consider doing away with pluggable grid systems. I think it's unnecessary and it seems reasonable to me that people using mosaic would need to buy into a certain grid system just for mosaic areas on the page. All grids do the same thing more or less.

**Comment by datakurre** [comment]
To be honest, the grid annotation syntax could probably be replaced with bs grid classes without loss of information. Also the current trend seems to be towards BS 3/4 -style grid classes.

Meanwhile, we could simply replace deco CSS with BS3/4 based grid by building BS3/4 grid with mosaic class names.
