### ISSUE TITLE
Format menu is shown even if there are no format actions defined

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#238]
Steps to reproduce on plone.app.mosaic 1.0 on Plone 5.0.x:

Remove all formats in registry:

```
   <!-- Remove formats  -->
  <records interface="plone.app.mosaic.interfaces.IWeightedDict"
           prefix="plone.app.mosaic.format_categories.tile" remove="True">
  </records>

  <records interface="plone.app.mosaic.interfaces.IWeightedDict"
           prefix="plone.app.mosaic.format_categories.row" remove="True">
  </records>
```

The Format menu should not be available at all, but is with an empty box:
![18-08-2016 13-25-39](https://cloud.githubusercontent.com/assets/339384/17772266/385ca9fe-6548-11e6-9f56-aa045c1e3ccf.png)

Removing the format action as a whole

```
<!-- Remove formats  -->
  <records prefix="plone.app.mosaic.secondary_actions.remove"
           interface='plone.app.mosaic.interfaces.IAction' remove="True">
  </records>

  <records interface="plone.app.mosaic.interfaces.IWeightedDict"
           prefix="plone.app.mosaic.secondary_actions.format.items.format" remove="True">
  </records>
```

throws a JavaScript error when accessing the Mosaic edit page of a page:
![18-08-2016 13-52-08](https://cloud.githubusercontent.com/assets/339384/17772803/23081752-654b-11e6-9637-3c5a822b371b.png)

**Comment by gforcada** [comment]
@tomgross fair point, but is there any practical usage of not having formats at all?

**Comment by tomgross** [comment]
In our setup we have backend (barceloneta) and frontend (custom) layout strictly separated. They even have a different grid system. The rewriting is done with Diazo. Any format applied to the backend is meaningless in the frontend.

**Comment by vangheem** [comment]
@tomgross I think you'd also need to remove the format button registration as well in order for that to work.

Or just use a css style to hide it instead.

Closing for now. Please re-open if that still does not work for you.
