### ISSUE TITLE
provide tile to include existing images from Plone

### ISSUE THREAD

**Issue by MrTango** [plone/plone.app.mosaic#241]
...instead of uploading a new one from the local hard-drive.
Eventually we can use also the "existing content" tile and integrate image including scaling in it.

**Comment by agitator** [comment]
or extend the already available image tile

**Comment by vangheem** [comment]
Maybe it's better to remove the current image tile implementation and instead advise users to use the image button on tinymce?

**Comment by zopyx** [comment]
What you actually want is an image title where you could select multiple existing images.  As a display option you can choose from horizontal/vertical mode in order display images as a row or as a column or as a vision: render all selected images as a slider...

**Comment by vangheem** [comment]
Maybe that is more for the listing tile?

Perhaps the listing tile should allow you to select specific items. Then one of the displays for it would be "gallery" or "slider", etc.

However, typically with galleries and sliders you want other configuration options so perhaps that use-case should be handled as it's own tile.

**Comment by zopyx** [comment]
Possibly yes, depends on the assumption that a tile would imply always a fixed rendering method.

**Comment by vangheem** [comment]
I'm going to close this for now. To include existing images in plone, we advise to use tinymce to select and insert images.
