### ISSUE TITLE
default-layout-screenshot.png not found

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.mosaic#243]
master branch as of 05.09.2016: missing default-layout-screenshot.png

![screenshot 2016-09-05 um 10 22 10](https://cloud.githubusercontent.com/assets/594239/18241728/00591fe2-7353-11e6-977c-a47f059424e7.png)
![screenshot 2016-09-05 um 10 22 01](https://cloud.githubusercontent.com/assets/594239/18241727/00566aa4-7353-11e6-9c8f-64c8ca6fcb0d.png)

**Comment by vangheem** [comment]
Are you on master? I thought this was fixed.

**Comment by vangheem** [comment]
fixed here: https://github.com/plone/plone.app.mosaic/commit/95b70d4f171d06ce7227a486c1073e636c4e1695
