### ISSUE TITLE
Horizontal text blocks in edit mode rendered improperly in view mode

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.mosaic#244]
master as of 05.09.2015:

I added three 'text' blocks for having a three column layout in edit mode.
The text blocks are not rendered properly in view mode.

![screenshot 2016-09-05 um 10 28 04](https://cloud.githubusercontent.com/assets/594239/18241820/85406ecc-7353-11e6-996b-4f0bef619c0c.png)
![screenshot 2016-09-05 um 10 27 30](https://cloud.githubusercontent.com/assets/594239/18241819/853c5da0-7353-11e6-9df0-c153fda5a41f.png)

**Comment by vangheem** [comment]
Yes, this is related to #230 and #231

**Comment by vangheem** [comment]
Fixed with https://github.com/plone/plone.app.blocks/pull/42
