### ISSUE TITLE
Visual overlap (table title)

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.mosaic#246]
Parts of the table editor overlap with multiple table rows
![screenshot 2016-09-05 um 10 37 06](https://cloud.githubusercontent.com/assets/594239/18242067/cf6919e4-7354-11e6-87fc-279f96af11b7.png)

**Comment by vangheem** [comment]
Yes and we need to rethink how we do a lot of these tinymce actions right now. This brings up a worse problem of how we're integrating with tinymce right now.

**Comment by zopyx** [comment]
Another overlap with an overlay :
![screenshot 2016-09-05 um 10 40 13](https://cloud.githubusercontent.com/assets/594239/18242156/303ba9bc-7355-11e6-9b32-21028dabf386.png)

**Comment by vangheem** [comment]
Commit fixes it about as good as we'll be able to with tinymce integration right now. Fixes the modal problems.
