### ISSUE TITLE
Relation with snippets?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.app.mosaic#25]
I just came across snippets: https://www.github.com/collective/snippets which in short allows you to put placeholders into your rich text (with TinyMCE) which later are rendered somehow to something different (dynamic content or some sort of thing).

This looks quite similar to tiles actually, but in a different approach as usually for that you will have different tiles (portion of text + image + portion of text lets say) while in snippets sense it would be just a single text that has a placeholder that at rendering time is changed to something else.

I think that both approaches have valid use cases (I see myself using both approaches for a newspaper site myself), so the question would be: is that approach from snippets somehow going to be also implemented/supported by blocks/tiles/mosaic?

**Comment by datakurre** [comment]
As a closing note, I remember fixing c.tinymcetiles to work with p.a.blocks 2.0.

**Comment by djay** [comment]
BTW I suggest to the author of snippets that it could be generalised using
tinmcetiles. Is a snippet is just a kind of tiles where you pick your
snippet. Or you create new tiles types for each snippet.
What tinymcetiles branch needs is to be changed to use tinymces ability to
have read only elements which I believe snippets does. This allows the
elements to be moved around while retaining their ability to live preview
inline with resorting to an image.
But I still think the easy if use of pasting and editing short codes has
its merits.
