### ISSUE TITLE
Disable Mosaic Editor on add forms

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#251]
Should we? @vangheem @jensens @agitator Are you using Mosaic on add-forms?

Disabling Mosaic on add forms would ensure that we have local container for files and images if we deprecate / remove attachment and image tiles.

This an be easily done by removing add-form support form LayoutWidget-class in plone.app.mosaic.widget.

We could also follow the way of plone.app.page further:

* Let's register custom add form for Mosaic types, and let that add form only show title and descrpition
* Saving the add form would open the content in edit mode

**Comment by jensens** [comment]
I like the idea of having a minimal add form and then redirecting to mosaic editor mode.

**Comment by vangheem** [comment]
I'll work on this.
