### ISSUE TITLE
Can we remove dependency on multifile

### ISSUE THREAD

**Issue by vangheem** [plone/plone.app.mosaic#257]
it seems to me that `plone.formwidget.multifile` should not be a dependency.

**Comment by gforcada** [comment]
It seems to be used on plone.app.standardtiles.attachment.py:

```
from plone.formwidget.multifile.widget import MultiFileFieldWidget
```

**Comment by vangheem** [comment]
No, we can not remove right now. Even if we remove those tiles, we need to provide the code for them for bbb...
