### ISSUE TITLE
Registration of Layouts in FTI

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.mosaic#262]
Move registration-mapping of content layouts to portal types to FTI.
- add new properties `available_layouts` and `default_layout` to dexterity FTI.
- let them get picked up on profile import
- change vocabulary to read the values from FTI. 
  - if empty there read BBB from registry
  - if in registry use and write out deprecation warning

**Comment by gforcada** [comment]
Just a note but when we are full mosaic we should deprecate all the following FTI properties (or at least warn about them not being used):

```
add_view_expr
default_view
default_view_fallback
immediate_view
view_methods
```
