### ISSUE TITLE
Layout issue with Text Area Tile if you have only an image in it

### ISSUE THREAD

**Issue by MrTango** [plone/plone.app.mosaic#277]
If you have a Text Area Tile which only contains an image, the tile border and hover marker are not surrounding the whole area, instead you see the image but can not edit it y clicking on it. You have to select a small line on the top of the tile, which is not so easy. It would be better to have the border and marker around the image too.

**Comment by vangheem** [comment]
Can you show me this? I can not reproduce this.

**Comment by vangheem** [comment]
Closing for now. Can no longer reproduce with latest. Will reopen if we can reproduce.
