### ISSUE TITLE
How is Mosaic content indexed?

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#292]
If I add arbitrary text to a mosaic page, how do I make it available to SearchableText. If it is part of a field, this can be done with an indexing adapter but how does it work for a text only tile with no DX field as storage?

**Comment by datakurre** [comment]
plone.app.blocks provides SearchableText indexers
with and without collective.dexteritytextindexer.

Right now I don't remember if the first one is registered by default.

**Comment by neilferreira** [comment]
Related: https://github.com/plone/plone.app.blocks/issues/25

I'll be addressing this in coming weeks

**Comment by hvelarde** [comment]
FYI, this is how we implement that feature: https://github.com/collective/collective.cover/pull/556

**Comment by tomgross** [comment]
https://github.com/collective/collective.dexteritytextindexer takes care of this.
