### ISSUE TITLE
Missing plone standard tile for Image in 2.0

### ISSUE THREAD

**Issue by 1letter** [plone/plone.app.mosaic#295]
After i updated to p.a.m.2.0 my Image Tiles are not editable. On the side of tile i have a tab with the label 'Unknown'. What is the reason of removing the Tile in p.a.m 2.0? If i enabled/added the tile in my registry.xml the operation comes back and the tile is configurable. I see in the Menu of Customizing the Mosaic Layout, that many Tiles are removed, why?

**Comment by vangheem** [comment]
We decided to remove it because having yet another way to create images/content in plone wasn't a good idea. It caused other issues with storage and versioning as well.

For now at least, we're suggesting that users stick with the rich text field to add images.

**Comment by 1letter** [comment]
Thanks for the Info.
