### ISSUE TITLE
Is it at all possible to have python code inside of a layout without doing so via a tile?

### ISSUE THREAD

**Issue by neilferreira** [plone/plone.app.mosaic#297]
I've got a situation where I need to achieve the following:

I have a content type: Page

Landing page has a layout: PageLayout

My layout needs to do something like:
[draggable section of tiles]
[hard-coded section of layout, which displays a fixed list of elements that have to be generated using TAL templates]
[draggable section of tiles]

What would be an easy way to achieve this?  What I imagined we could do is create a transient tile that is automatically included on the page that is included in the hard-coded section.  Any ideas on how to achieve this?

**Comment by vangheem** [comment]
FWIW, castle mosaic layouts are chameleon enabled. Hopefully will have it open sourced and installers soon.
