### ISSUE TITLE
plone-mosaic.css not loading

### ISSUE THREAD

**Issue by ginetsl** [plone/plone.app.mosaic#298]
The mosaic resource bundle is depending on plone-logged-in ( Expression: python: member is not None ), but there are styles in plone-mosaic.css that are needed when not authenticated.

In my case, the most visible, not desired effect is the lack of ::before and ::after selectors for div.mosaic-grid-row.

---

Plone = 5.0.6
plone.tiles = 1.8.0
plone.app.tiles = 3.0.0
plone.app.standardtiles = 2.0.0rc1
plone.app.blocks = 4.0.0rc1
plone.app.drafts = 1.1.1
plone.app.mosaic = 2.0.0rc1

**Comment by datakurre** [comment]
What exactly is missing visually? I don't remember those selectors having something for view mode.

**Comment by ginetsl** [comment]
plone-mosaic.css defines ::after for .mosaic-grid-row, to make a "clear:both".
I am attaching screenshots of examples.
![logged in](https://cloud.githubusercontent.com/assets/19911634/18994903/dad9a8dc-86f7-11e6-985b-ced590a676d9.png)
![logged out](https://cloud.githubusercontent.com/assets/19911634/18994902/dad2e812-86f7-11e6-9ac8-b98d7db02e5c.png)

**Comment by datakurre** [comment]
That's confusing. I agree on that.

@agitator Would you have opinion on this? It's wrong that edit has clear:both and view not, but should we a) add clear:both to view mode or b) get rid of it also in edit mode? I don't remember if the editor really needs that style.

**Comment by ginetsl** [comment]
Causes inconsistency in 
![middle row-logged](https://cloud.githubusercontent.com/assets/19911634/18997131/11d32f08-8701-11e6-9e4a-9adba2d77cd1.jpg)
![middle row-logged out](https://cloud.githubusercontent.com/assets/19911634/18997130/11d29930-8701-11e6-8d5a-ad3ea87a59f1.jpg)

middle rows too:

**Comment by datakurre** [comment]
@ginetsl Thanks.

@agitator @vangheem Would you see any reason to not have clear:both before rows in the default grid? I would be ok for adding that.

**Comment by litsol** [comment]
I have the same issue. The only difference between the html for logged-in and anonymous viewers is the presence or absents  of: logged-in.{css.js} and  plone-mosaic.{css,js}. 

![image](https://cloud.githubusercontent.com/assets/326217/20802919/daf408a4-b7ed-11e6-9fdb-23d3d222a650.png)

And as ginetsl wrote, plone-mosaic.css is needed for anonymous viewing. 

Here is the entry for plone.bundles/mosaic in mosaic's registry.xml

![image](https://cloud.githubusercontent.com/assets/326217/20803240/c86d7868-b7ee-11e6-852e-7bafc8ec9851.png)

The 'expression' and 'depends' keys control the logged-in behavior. I can change these values TTW via Plone's Resource Registry Tool. I would rather override them in the mosaic product; either programitically or in generic-setup. Any suggestions how to accomplish this would be very welcome.

**Comment by datakurre** [comment]
@ginetsl @litsol Could you confgirm, if this is this still an issue with https://pypi.python.org/pypi/plone.app.mosaic 2.0.0rc3

FWIW, plone-mosaic.(js|css) should only be required for logged-in users (to be more specific, only for the editor), but mosaic-grid -bundle is required for all users (unless custom theme with custom grid is used). I believe that mosaic-grid-bundle was missing in 2.0.0rc1.

**Comment by ginetsl** [comment]
Yes, I just updated yesterday to 2.0.0rc3 and can confirm this is not longer an issue. Thanks!!

**Comment by litsol** [comment]
I encounter the same problem with the new version.

I specify the new 2.0.0rc3 egg in my buildout,  run buildout, start the instance and reinstall mosaic - so I can confirm that this is the version that is installed. However, neither the the mosaic-grid.css nor the mosaic-grid.js is included in the html presented to the anonymous viewer. They are both included in the html presented to the logged in viewer. 

Here is a screenshot while logged in:

![mosaic](https://cloud.githubusercontent.com/assets/326217/21102847/358c1a78-c080-11e6-93c0-1c7e14f54ed9.png)

Here is a screenshot while not logged in:

![mosaic1](https://cloud.githubusercontent.com/assets/326217/21102856/3b822dd2-c080-11e6-9eb0-758b5cb3b6eb.png)

Here is the Resource Registry. The problem occurs when the 'Depends' and 'Expression' values are set.

 
![mosaic2](https://cloud.githubusercontent.com/assets/326217/21102859/413adf08-c080-11e6-9e8d-88c4d30fb4af.png)


What can I do to help you isolate this behaviour?

**Comment by datakurre** [comment]
How about if you rebuild "Plone" bundle?

(mosaic-grid should be included in "default" "meta bundle", but I don't know in detail, how those get updated)

**Comment by litsol** [comment]
Thanks for your quick response.

I have rebuild the plone plone-logged-in and mosaic bundles, but the
behavior is the same.

I have tried upgrading mosaic in an existing plone site, creating a new
plone site with the specific mosaic revision, and creating a new zope
instance with a plone site with the specific mosaic revision. The mosaic
behavior is the same in all cases.

If you are willing to make suggestions, I am willing to keep looking for
the reason for this behavior.

**Comment by datakurre** [comment]
@litsol How does your configuration for mosaic-grid-bundle
look like? Maybe we can manually enable that for all users.
