### ISSUE TITLE
TinyMCE Formats Submenu invisible

### ISSUE THREAD

**Issue by mr-rob** [plone/plone.app.mosaic#301]
With larger sites, or larger text blocks, the submenu "Formats" isn't visible anymore.
Steps to reproduce:
- Create new site
- Add Text
- Click on "Formats"
  ![mosaic_tinymce_floating](https://cloud.githubusercontent.com/assets/5370769/19192114/65445668-8ca5-11e6-891c-14504ca40f31.png)

**Comment by fhnwba** [comment]
This happens on long pages, when the text field is far below.

**Comment by tomgross** [comment]
@vangheem @agitator Have you seen this? Any idea how to fix it?

**Comment by vangheem** [comment]
What version are you on? I thought I fixed all that craziness.

**Comment by mr-rob** [comment]
Plone-5.0.6
plone.app.mosaic-2.0.0rc2
Firefox 45.4.0 and Chrome 54

**Comment by datakurre** [comment]
I can reproduce this, so looking into this.

**Comment by datakurre** [comment]
Floating TinyMCE panels seem to check position of document.body for some reason. With CSS body { position: relative; } this works already better. Only format menus with oversized TinyMCE remain hidden.

**Comment by datakurre** [comment]
I believe, I fixed this. There was a typo in the original fix by Nathan. I also added body { position: relative;} because that affects, how TinyMCE calculates fixed positions.

**Comment by mr-rob** [comment]
@datakurre unfortunately the submenu still disappears for me…

**Comment by datakurre** [comment]
@mr-rob If you have tried the current master, have you tried to rebuild the bundles first? (Should be possible either from resource registry or by running make install and make in repository.)

I did not include rebuilt bundle, but will only build it for release.

**Comment by mr-rob** [comment]
@datakurre that did the trick, thanks!
