### ISSUE TITLE
Adding a fieldset to tile schema stops fieldset's fields from being saved

### ISSUE THREAD

**Issue by neilferreira** [plone/plone.app.mosaic#303]
Unsure if this is a plone.app.tiles or mosaic issue?

Example:

Adding a "body" field to your tile:

```
    body = RichText(
        title=u'Body text',
        required=True
    )
```

Sends the payload from the tile editor as:

```
Content-Disposition: form-data; name="my.site.tiles.text.body"
<p>sadfsd</p>
Content-Disposition: form-data; name="my.site.tiles.text.body.mimeType"
text/html
```

Moving your field into a fieldset, ie:

```
    model.fieldset(
        'body',
        fields=['body'])
```

Changes the payload to:

```
Content-Disposition: form-data; name="form.widgets.body"
<p>bodyyyy</p>
Content-Disposition: form-data; name="form.widgets.body.mimeType"
text/html
```

As a result, the data manager is not saving thee values, defaulting them to None.

**Comment by datakurre** [comment]
@neilferreira Nice catch! plone.app.tiles, but does not hurt to track this also where.

It could be that plone.app.tiles was create too early for it to base its forms on top of plone.supermodel and plone.autoform, and therefore does not work properly with plone.autoform magic.

**Comment by datakurre** [comment]
Well. It does inherit AutoExtensibleForm.

**Comment by datakurre** [comment]
@neilferreira Could be this:

https://github.com/plone/plone.app.tiles/blob/master/plone/app/tiles/browser/base.py#L80

TileForms override widgetUpdate, but only set widget prefix for the main from widgets, ignoring form's groups' widgets (fieldsets).

**Comment by datakurre** [comment]
@neilferreira FYI. I have now a pull to fix fieldset support in plone.app.tiles >= 3.1.0

https://github.com/plone/plone.app.tiles/pull/23

I still need to write a test for that, so if you want that now, you need to package p.a.tiles by yourself.

**Comment by mauritsvanrees** [comment]
Looks like this was fixed.
