### ISSUE TITLE
Not able to change/shift column width

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#307]
The handle to shift column width doesn't appear for me.
This should still be possible, right?
(p.a.mosaic buildout master)

![img_2734](https://cloud.githubusercontent.com/assets/365761/20030208/84b211da-a360-11e6-8b50-e1993457850d.JPG)

**Comment by datakurre** [comment]
@agitator I cannot reproduce #307 (this) or #308 at Heroku demo made from 2.0.0rc2.

http://plonemosaic200rc2.herokuapp.com/Plone/asdfsa

The screenshot shows that something is terrible wrong with styles, because all "mosaic-grid-rows" are stacked on top of the page.

**Comment by datakurre** [comment]
@agitator The only changes in master after 2.0.0rc2 is your fixes for grid system (which you refactored at Mephisto sprint), so you are probably the best choice to figure his out :)

So, probably both this #307 and #308 are related to CSS. The editor relies on properly placed (and sized) dom elements for resizing and "new row" features.

**Comment by agitator** [comment]
darn, was pretty sure we tested that... will look into it ;-)

**Comment by datakurre** [comment]
@agitator Would you be able to look at this? Otherwise I must revert https://github.com/plone/plone.app.mosaic/pull/300

**Comment by agitator** [comment]
it's still on my list, hope to find the time later this week

**Comment by agitator** [comment]
@datakurre should be fixed now, can you have a look at it?
seems @import "mosaic.grid.less"; has to be included in mosaic.pattern.less

but isn't mosaic.grid.css already loaded? do you know why this is necessary?

**Comment by jensens** [comment]
I can confirm #316 fixes the bug.

**Comment by datakurre** [comment]
@agitator I'll try to look into that including issue later.
