### ISSUE TITLE
Not able to create new full width row by dragging

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#308]
The full-width-row-insert-marker doesn't show at the bottom of the page
This should still be possible, right?
(p.a.mosaic buildout master)

![img_2735](https://cloud.githubusercontent.com/assets/365761/20030263/0cd8e0ce-a362-11e6-9b05-028c27ba695e.JPG)

**Comment by datakurre** [comment]
Does it work with alt-modifier pressed?

But, I do recall that Nathan noticed that already at Mephisto sprint, but I thought it was fixed.

**Comment by agitator** [comment]
there is no marker visible at all bellow the three columns, even with alt-modifier

**Comment by jensens** [comment]
I can confirm #316 fixes the bug. Alt-Modifier works.
