### ISSUE TITLE
mark_view is missing 

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#312]
after merge of https://github.com/plone/Products.CMFPlone/commit/78456286b47c29dd6409ea269450851d87fee55e mark_view is missing and @@plone_layout/mark_view should be used

not 100% sure how to update
https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/browser/main_template.py#L43
https://github.com/plone/plone.app.standardtiles/blob/master/plone/app/standardtiles/portlets/utils.py#L37
https://github.com/plone/plone.app.standardtiles/blob/master/plone/app/standardtiles/templates/existingcontent_view.pt#L36
https://github.com/plone/plone.app.tiles/blob/master/plone/app/tiles/browser/layout.pt#L11

**Comment by agitator** [comment]
@datakurre ping?

**Comment by thet** [comment]
Adressed by this: https://github.com/plone/plone.app.mosaic/pull/311

**Comment by thet** [comment]
Fixed by: https://github.com/plone/plone.app.mosaic/pull/311#issuecomment-260460124
