### ISSUE TITLE
Bug css missing for responsive design

### ISSUE THREAD

**Issue by rafaeltcc** [plone/plone.app.mosaic#317]
Sorry for my ignorance.

I have installed mosaic and I added 3 rich text columns A, B and C. When I resize the page the columns are narrowed, but they don't flow as expected in a liquid design. I mean, the columns aren't converted to rows and rearranged one under the other. 
A
B
C

I tried the bootstrap site layout template, I thought this would help, but the same happens.

**Comment by datakurre** [comment]
@rafaeltcc Would you be able to reproduce that with the latest versions at http://ploneappmosaic200rc3.herokuapp.com/Plone (admin:admin) and report back the url with the example?

**Comment by rafaeltcc** [comment]
No, it works great in the latest version. Thanks a lot again

**Comment by rafaeltcc** [comment]
@datakurre Although it works flawlessly in the herokuapp link you sent me. It does not work the same way in a Vanilla Plone 5.0.6 with plone.app,mosaic200rc3 as the only addon installed. When I resize my browser it keeps squeezing the columns and wont rearrange them (see image below). What can be causing this difference? Is there any other configuration set in the heroku deployment?

The only thing wrong in  my log is this raised conflict error

2016-12-12 12:26:04 INFO ZPublisher.Conflict ConflictError at /test/capa/@@edit-tile/plone.app.standardtiles.html/3d7366d3-fb32-4a5a-a8c0-80d002b6773c: database conflict error (oid 0x4d01, class plone.app.drafts.draft.Draft) (5 conflicts (0 unresolved) since startup at Mon Dec 12 12:17:21 2016)


![captura de tela de 2016-12-12 12-32-21](https://cloud.githubusercontent.com/assets/3977779/21102924/64824fbe-c067-11e6-8afd-eeef9dd86861.png)

**Comment by rafaeltcc** [comment]
Inspecting the elements I found a difference in the css from the version I have installed in my local machine and the one from heroku.
![local](https://cloud.githubusercontent.com/assets/3977779/21103748/e42cede8-c06a-11e6-95cf-96c8f65f4fe4.png)
![heroku](https://cloud.githubusercontent.com/assets/3977779/21103752/e7ce3236-c06a-11e6-89e1-745369c7a48c.png)

**Comment by rafaeltcc** [comment]
I found out that although I can't get the responsive behaviour  in the edit mode, when I save my mosaic and view it everything works as expected.
