### ISSUE TITLE
"Format" and "Insert" buttons do not appear when going into Edit mode on item with 1 layout

### ISSUE THREAD

**Issue by neilferreira** [plone/plone.app.mosaic#321]
When you have a content type with a single layout and access the "Edit" screen there is no Insert or Format button in the top right corner

Clicking in any part of the web page automatically shows the buttons.

**Comment by datakurre** [comment]
Usually those only appear after you "Layout" => "Customize" a layout. Is there somewhere a settings, which makes "customizeable" layout the default action?

**Comment by datakurre** [comment]
@neilferreira Any change that you could confirm this been fixed for you with the current master?
