### ISSUE TITLE
Existing content tile referencing removed page causes issue

### ISSUE THREAD

**Issue by rileydog** [plone/plone.app.mosaic#323]
working with Mosaic, all seemed fine - I didn't get any errors.  However, when I checked the logs for an unrelated reason, I found this error.  I had been testing Mosaic and you can see the reference to "standard tiles" I assume that is Mosaic.

2016-12-02T20:52:53 ERROR Zope.SiteErrorLog 1480711973.560.300607266969 http://wayne.lwhsboosters.org/Wayne/front-page/@@plone.app.standardtiles.existingcontent/d13a4dad247f4b21b59a51dad0ece49b1

Traceback (innermost last):
Module ZPublisher.Publish, line 127, in publish
Module ZPublisher.BaseRequest, line 508, in traverse
Module ZPublisher.BaseRequest, line 344, in traverseName
Module plone.tiles.tile, line 77, in publishTraverse
Module plone.tiles.tile, line 51, in getitem
Module plone.tiles.tile, line 101, in url
Module zope.traversing.browser.absoluteurl, line 33, in absoluteURL
Module zope.traversing.browser.absoluteurl, line 81, in call
Module plone.tiles.absoluteurl, line 75, in str
Module plone.tiles.data, line 109, in get
Module plone.app.blocks.layoutbehavior, line 360, in contains
Module plone.app.blocks.layoutbehavior, line 354, in get
Module plone.memoize.view, line 47, in memogetter
Module plone.app.blocks.layoutbehavior, line 348, in getitem
Module plone.jsonserializer.deserializer.converters, line 30, in schema_compatible
Module zope.component._api, line 107, in getMultiAdapter
Module zope.component._api, line 120, in queryMultiAdapter
Module zope.component.registry, line 238, in queryMultiAdapter
Module zope.interface.adapter, line 532, in queryMultiAdapter
Module plone.jsonserializer.deserializer.converters, line 48, in schema_dict_converter
Module plone.jsonserializer.deserializer.converters, line 30, in schema_compatible
Module zope.component._api, line 107, in getMultiAdapter
Module zope.component._api, line 120, in queryMultiAdapter
Module zope.component.registry, line 238, in queryMultiAdapter
Module zope.interface.adapter, line 532, in queryMultiAdapter
Module plone.jsonserializer.deserializer.converters, line 67, in from_unicode_converter
Module zope.schema._field, line 322, in fromUnicode
Module zope.schema._bootstrapfields, line 183, in validate
Module zope.schema._field, line 338, in _validate
ConstraintNotSatisfied: (u'a5ec510b4f094ab9a7e2a093cde5f1f8', 'content_uid')
==================

**Comment by datakurre** [comment]
Nice catch. Thanks for the report. Fixing this is a bit involved, but must be done. I should be able to dive into this in the next week at last.

**Comment by datakurre** [comment]
@rileydog Thanks. This should now been fixed with the next plone.app.standardtiles release, possibly early next week.
