### ISSUE TITLE
reference to tiles in instance file when plone shutdown

### ISSUE THREAD

**Issue by rileydog** [plone/plone.app.mosaic#326]
Hello,   sorry, I don't know if this is a Mosaic issue.  I filed a previous bug report at your request (from plone.community).  I hope I guessed right here.  

2016-12-07T15:44:22 ERROR Zope.SiteErrorLog 1481125462.980.347194821239 http://wayne.lwhsboosters.org/Wayne/front-page/@@plone.app.standardtiles.existingcontent/d13a4dad247f4b21b59a51dad0ece49b
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 508, in traverse
  Module ZPublisher.BaseRequest, line 344, in traverseName
  Module plone.tiles.tile, line 77, in publishTraverse
  Module plone.tiles.tile, line 51, in __getitem__
  Module plone.tiles.tile, line 101, in url
  Module zope.traversing.browser.absoluteurl, line 33, in absoluteURL
  Module zope.traversing.browser.absoluteurl, line 81, in __call__
  Module plone.tiles.absoluteurl, line 75, in __str__
  Module plone.tiles.data, line 109, in get
  Module plone.app.blocks.layoutbehavior, line 360, in __contains__
  Module plone.app.blocks.layoutbehavior, line 354, in get
  Module plone.memoize.view, line 47, in memogetter
  Module plone.app.blocks.layoutbehavior, line 348, in __getitem__
  Module plone.jsonserializer.deserializer.converters, line 30, in schema_compatible
  Module zope.component._api, line 107, in getMultiAdapter
  Module zope.component._api, line 120, in queryMultiAdapter
  Module zope.component.registry, line 238, in queryMultiAdapter
  Module zope.interface.adapter, line 532, in queryMultiAdapter
  Module plone.jsonserializer.deserializer.converters, line 48, in schema_dict_converter
  Module plone.jsonserializer.deserializer.converters, line 30, in schema_compatible
  Module zope.component._api, line 107, in getMultiAdapter
  Module zope.component._api, line 120, in queryMultiAdapter
  Module zope.component.registry, line 238, in queryMultiAdapter
  Module zope.interface.adapter, line 532, in queryMultiAdapter
  Module plone.jsonserializer.deserializer.converters, line 67, in from_unicode_converter
  Module zope.schema._field, line 322, in fromUnicode
  Module zope.schema._bootstrapfields, line 183, in validate
  Module zope.schema._field, line 338, in _validate
ConstraintNotSatisfied: (u'a5ec510b4f094ab9a7e2a093cde5f1f8', 'content_uid')
------
2016-12-07T19:24:42 INFO plone.app.theming.policy local cache invalidated on thread 140296681420544
------
2016-12-07T19:24:42 INFO plone.app.theming.policy initializing local cache on thread 140296681420544 for http://wayne.lwhsboosters.org/Wayne::barceloneta
------
2016-12-07T19:24:49 INFO plone.protect auto rotating keyring _system
------
2016-12-07T19:24:49 INFO plone.protect auto rotating keyring _forms
------
2016-12-07T19:24:49 INFO plone.protect auto rotating keyring _anon
------
2016-12-07T19:24:49 INFO plone.protect auto rotating keyring _system
------
2016-12-07T19:24:49 INFO plone.protect auto rotating keyring _forms
------
2016-12-07T19:24:49 INFO plone.protect auto rotating keyring _anon

**Comment by datakurre** [comment]
Yes, I believe this was the same as https://github.com/plone/plone.app.mosaic/issues/323

**Comment by datakurre** [comment]
Yet, this should not be a reason for Plone to shutdown.

To be clear, this immediate issue will be fixed in the next p.a.standardtiles release next week. Still, it is not the real reason for Plone to shut down. Normally these exceptions are just logged and HTTP 500 returned (Internal Server Error), and on the next request everything should continue as before.
