### ISSUE TITLE
Translation not possible with mosaic activated

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#330]
With Plone 5.0.6 and plone.app.mosaic 2.0rc2 activated the babel_view of p.a.multilingual is not accessible if mosaic is activated. It switches automatically to the layout_view.

A cumbersome workaround is to turn of layout view temporarily for translation and switch it on afterwards.
I consider this issue a blocker for a final 2.0 release.

**Comment by datakurre** [comment]
Thanks for checking that. What do you mean with "it switching automatically to layout_view"?
