### ISSUE TITLE
content listing schema

### ISSUE THREAD

**Issue by iham** [plone/plone.app.mosaic#343]
might be a stupid question:

why is the schema of content listing not derived from plones collection schema?
(dry)

**Comment by datakurre** [comment]
They were historically developed at the same time, and back then Deco was designed to be used without plone.app.contenttypes.

Agreed that feature parity is what everyone expects. Yet, too much options make tiles hard to configure in overlay.

**Comment by agitator** [comment]
a client of mine want to use title and description within the contentlisting tile.
shall we add those fields and control visibility of thoses fields with checkboxes?

**Comment by datakurre** [comment]
I'd prefer simply creating and registering a new listing template. Would that be ok? A could have more built-in templates there.

**Comment by agitator** [comment]
but where should the title and description come from, if it's just a template override for that tile?

**Comment by agitator** [comment]
adding a richtext tile for that information is not the same layoutwise

**Comment by datakurre** [comment]
Right. I forgot that. So, adding title and description to the tile schema actually makes sense. So, please do :)

Only possible issue is that the form is already a bit long, but I do have fix to support fieldsets / tabs in plone.app.tiles, but I still need to write a test for that.

**Comment by agitator** [comment]
https://github.com/plone/plone.app.standardtiles/pull/64
