### ISSUE TITLE
Suggestion for improving listing in Mosaic

### ISSUE THREAD

**Issue by rafaeltcc** [plone/plone.app.mosaic#367]
Hi everyone,

I see there is a Gsoc student improving the list tiles from mosaic.

I don't know if this is the right place, but I just had to solve a problem on how to display item from the catalog of another plone site in the same installation. This is done by traversing...

What do you think? Wouldn't it be nice that the user could list content from other sites also? Or is this to specific, or outside mosaic scope.

See the discussion:
https://community.plone.org/t/traverse-content-from-other-plone-site-same-installation-ttw/4240/14

**Comment by djay** [comment]
@rafaeltcc Probably not the right place. The normal way this is done is to use some other plugin like feedfeeder to bring the content into plone and then use some method of customising a listing to display it like collective.listingview. This would work the same with any new way to do listings using mosaic.
