### ISSUE TITLE
Content lost with big/complex mosaic pages

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#382]
When you open the mosaic editor all tiles are loaded with independend subrequests. If you have many tiles this process can take a while and if your page is big you may not even see when all tiles are fully loaded into the editor.

If you hit save *before* all tiles are fully loaded Mosaic overrides the tiles which are not yet loaded with no value.

I guess this issue can be solved by disabeling all buttons (except Cancel) in the mosaic toolbar until all tiles are fully loaded.

**Comment by datakurre** [comment]
This probably only happens for text tiles, because there's code to ensure that all text tiles get saved.

**Comment by datakurre** [comment]
I agree, this is a blocker. I'll still release RC8 first with that JS issue fixed that I accidentally introduced, and hopefully I can look into this next week.

**Comment by tomgross** [comment]
@datakurre Any news on this? Anything I can help?
I found "loosing content" in richtext is especially a problem if you have video tiles embeded. The additional latency when accessing external services seems to confuse the mosaic editor.

**Comment by datakurre** [comment]
Not yet. It might be that I can’t return to work on editor before the conf :(

Some time ago I introduced queue for fixing issue with simultaneous tile saves on save. Possible that could be used so that save remains disabled until all tiles are loaded through the queue. On error that might leave save disabled, but that’s probably good.

**Comment by petschki** [comment]
is this still an issue? I was not able to reproduce this with latest plone 5.1 and mosaic versions ... created a mosaic page with huge richtext and 10 video embedding tiles ... hit save while loading videos and still everything is in place ...

**Comment by tomgross** [comment]
No I could not reproduce this either for a long time.
