### ISSUE TITLE
Display Tile Type on hover and/or select

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#39]

**Comment by datakurre** [comment]
This may be duplicate of #37

**Comment by datakurre** [comment]
This was limited by purpose, but this change can easily be reverted later if required.

**Comment by datakurre** [comment]
![nayttokuva 2015-05-03 kello 5 03 22](https://cloud.githubusercontent.com/assets/160447/7443425/ce1da126-f151-11e4-955e-6c53e77a1250.png)

**Comment by gforcada** [comment]
Awesome!!

**Comment by simahawk** [comment]
thanks asko! :)
