### ISSUE TITLE
Mosaic not showing german Umlaute

### ISSUE THREAD

**Issue by joplono** [plone/plone.app.mosaic#402]
In Rich Text Tile image caption on mouseover does not display german mutated vowels (Umlaute) 

Mosaic  2.0rc8

**Comment by jensens** [comment]
Works here with latest Mosaic 2.1
![screenshot from 2018-04-13 14 25 41](https://user-images.githubusercontent.com/157140/38734632-9e86eb22-3f26-11e8-8f4d-23026cb61a5f.png)
