### ISSUE TITLE
Mosaic looses all content

### ISSUE THREAD

**Issue by joplono** [plone/plone.app.mosaic#403]
After copyying and pasting a full page created with mosaic the whole content is lost.

 2.0rc8

**Comment by jensens** [comment]
is this using actions/contents copy/paste?

**Comment by joplono** [comment]
yes.

**Comment by jensens** [comment]
@joplono closed by accident?

**Comment by joplono** [comment]
Ups, yes, by accident.

But now it's ready to close as I found versions that will work.
