### ISSUE TITLE
version pins outdated

### ISSUE THREAD

**Issue by joplono** [plone/plone.app.mosaic#406]
At least the version pinning in [this official documentation](https://training.plone.org/5/ttw/mosaic.html)  needs an Update.

Mosaic will work fine in Plone 5.08 with these pins:

plone.tiles = 2.0.0b3
plone.subrequest = 1.8.1
plone.app.tiles = 3.0.3
plone.app.standardtiles = 2.2.0
plone.app.blocks = 4.1.1
plone.app.drafts = 1.1.2
plone.app.mosaic = 2.0rc8
plone.formwidget.multifile = 2.0
plone.jsonserializer = 0.9.5

**Comment by petschki** [comment]
version pins are updated in #414
