### ISSUE TITLE
TinyMCE gets initialized twice

### ISSUE THREAD

**Issue by frapell** [plone/plone.app.mosaic#407]
@datakurre Do you remember why this was needed here?

https://github.com/plone/plone.app.mosaic/blob/b93b809619cee3863178b6964ad7476635afd119/src/plone/app/mosaic/browser/static/js/mosaic.tile.js#L793

With latest TinyMCE (4.7.6) I'm observing that the toolbar won't open and I would get this error https://github.com/tinymce/tinymce/issues/2655 

For what I understand, TinyMCE loads asynchronously (was this not the case with previous versions?) and because of that line 793, a new pattern is created, but without properly cleaning up the previous initialization... even though there is code that should do that in https://github.com/plone/plone.app.mosaic/blob/b93b809619cee3863178b6964ad7476635afd119/src/plone/app/mosaic/browser/static/js/mosaic.tile.js#L1013 (I suspect because of tinymce being created async, however I don't quite understand why it was working before...)

Commenting out that line 793 solves the issue for me, and clicking on any of the richtext tiles would now show up the toolbar just fine...

Reading those "HACK HACK HACK" on top makes me think that this might have been something for old TinyMCE that is no longer needed, but I'm not sure...

**Comment by datakurre** [comment]
You are probably correct. Those lines are already years old. And it also works on older versions than your latest one?

Thanks!

**Comment by frapell** [comment]
I haven't tested it yet, will do so shortly and if so, will submit a pull request with that stripped away
