### ISSUE TITLE
Can't uninstall Mosaic from Plone 5.1

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.app.mosaic#418]
Plone 5.1.2 with the following Mosaic related versions:

```ini
[versions]
plone.app.blocks = 3.1.0
plone.app.drafts = 1.0
plone.app.mosaic = 1.0
plone.app.standardtiles = 1.0
plone.app.tiles = 2.2.1
plone.tiles = 1.5.2
```

On the Add-ons control panel configlet Mosaic appears listed as installed and the following message is show besides: **Warning** This product cannot be uninstalled!

**Comment by hvelarde** [comment]
removing all pins to bring latest versions of all dependencies results on the same error.

resuming: neither plone.app.mosaic 2.0rc8, nor plone.app.standardtiles 2.2.0, can be uninstalled from Plone 5.1.2.

**Comment by jensens** [comment]
so, this is solved now?

**Comment by hvelarde** [comment]
only for Mosaic 1.x; I still need to port the uninstaller to master branch.

**Comment by petschki** [comment]
@hvelarde portet your uninstall profile to Plone >= 5.x here https://github.com/plone/plone.app.mosaic/pull/430
