### ISSUE TITLE
Move TinyMCE Style Elements to separate Toolbar

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#42]
Most TinyMCE features are missing, e.g. create Link, add Image, ...

**Comment by datakurre** [comment]
As a note: items currently in "format"-menu can be moved into button-toolbar by setting their "favorite"-value in registry configuration into true.

**Comment by datakurre** [comment]
Fixed in https://github.com/plone/plone.app.mosaic/pull/111
