### ISSUE TITLE
Move Tile Left/Right out of Text Justify Menu

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#43]

**Comment by datakurre** [comment]
@robgietema Would you remember, why the format menu (usually containing only richtext formatting actions) contains also tile aligning action?

**Comment by datakurre** [comment]
Moved into new *Tile* -menu in https://github.com/plone/plone.app.mosaic/commit/9194b5a77adcdfe2d7a2822b1c6b3471f9bbf198
