### ISSUE TITLE
Image tile is broken

### ISSUE THREAD

**Issue by bloodbare** [plone/plone.app.mosaic#44]
Use the media repository to store an image tile and move the image tile to be transient.

**Comment by datakurre** [comment]
Commit, which removed the original image tile: https://github.com/plone/plone.app.standardtiles/commit/d40e0ad62ea8936fba420c5234bf6a3bafc706cd

**Comment by datakurre** [comment]
We can have working plone.app.drafts now, so persistent image tile without media repository would be ok, to make this easier.

**Comment by datakurre** [comment]
Fixed by adding new persistent image tile into stdtiles https://github.com/plone/plone.app.standardtiles/commit/530b6fb45f1391a91ab2b8a2e37afbdcf9768e12

It's a simple image tile with image and selected display scale (by forcing to use some of the configured image scales).
