### ISSUE TITLE
Check if renamed IRichTextBehavior class still existing mosaic layouts after upgrading to p.a.contenttypes 2.0.1

### ISSUE THREAD

**Issue by fredvd** [plone/plone.app.mosaic#444]
@petschki I'll create a new issue for this. Sorry for being so late to the game, I totally missed your question for me on the IRichtTextBehavior stuff in the pull request for Python 3 compatibility in #438. 

I've been using p.a.mosaic in production for 5-6 months, gained some more understanding and I though there's still an issue for anyone using Mosaic who will upgrade from plone 5.0/5.1 to 5.2 once it is released. In plone.app.contenttypes the IRichText and ILeadimage behaviors were renamed to fix the behavior registration, but p.a.contenttypes was bumped to 2.0.0 for this because it is a breaking change.  I noticed this, wrote issue #420  and did fix to the 'default' mosaic layouts you can activate in PR #426 , which was accidentally merged by @jensens while I was still thinking of the implications.

But wow.... I see this whole issue with storing the old dotted path might be solved now by 

https://github.com/plone/plone.app.contenttypes/pull/504
and the underlying feature in plone.behavior:
https://github.com/plone/plone.behavior/pull/19

The only question left, if this also works out for the dotted paths stored in all existing mosaic layouts on content items in a 5.0/5.1 site to 5.2 is, if we should still create an upgrade step to clean up the mosaic layouts anyway. At least, it won't break until the behavior is renamed 'again'. :-D

**Comment by petschki** [comment]
Well ... welcome to the party! 🎉 I‘ve upgraded today a project of us from 2.1.1 to 2.2.1 with the known good versions from `versions.cfg` ... everything went really smooth so far. Only the log messages from `plone.behavior` regarding the renamed behaviors ILeadImageBehavior and IRichTextBehavior showed up but as i recall correctly from the AlpineCitySprint this should resolve to the old interfaces. @pysailor worked on this and may have some detailed insights on this.

**Comment by pysailor** [comment]
Hi @fredvd 
not sure if this is relevant, but in p.a.upgrade there's an upgrade step to fix the FTIs of items that use either behavior in portal_types: plone/plone.app.upgrade#192
Maybe you need something similar in mosaic?

On the other hand, if you use the helper method `lookup_behavior_registration` to get the bahaviour, it will now also find IRichText and ILeadImage via their old dotted names. See the example at the bottom of https://github.com/plone/plone.behavior/blob/master/plone/behavior/directives.rst

**Comment by fredvd** [comment]
@petschki @pysailor Ok then we can close this if it now 'works'. Creating an upgrade step would not be as easy as replacing the behavior in the affected FTI's, but we would need to loop through all content in a site with the mosaic layout behavior and regexp replace the old dotted name in the html structure with the new name.... Too much risky work IMHO.
