### ISSUE TITLE
how to change tile-data via python

### ISSUE THREAD

**Issue by iham** [plone/plone.app.mosaic#447]
i am searching for a way to change the data of a tile inside a mosaic layout.
tried plone.tiles and datamangers all the way; even using the requestmethod. nothing worked in the end.

i can find the tiles inside the content_layout.
i can get the tile (view) using a traverser
i can read the data of the tile.
i can read the data from the datamanager.
i can set the data of that manager.

i can NOT persist that changes. no matter what i do.

so my simple question:
how to update the content_uid of the existingcontent-tile and store that.
no additional tiles; no changes. just the way mosaic does it, but not via browser.

any help?

the process is:
during generic setup creating a document; apply mosaic view; update layout a existing content tile; update this tile to point to an already created content-object. store this. done.

**Comment by datakurre** [comment]
@iham Oh, sorry, I didn't read properly. You already mentioned using the data managers. There should not be magic beyond that. If data manager get returns the change, it should be there.

**Comment by iham** [comment]
oh there is, but it is solved. (and leads to another ticket, but not in pa.mosaic)

the point is:
as tiles are made using TransientTiles the storage is not the same, as the sample shows.

i was pretty close but missed this in the end:
```
dataManager.storage.sync()
```

-> might be good documenting this?
