### ISSUE TITLE
"Error: Couldn't install: BTrees 4.4.1"

### ISSUE THREAD

**Issue by LeuAlmeida** [plone/plone.app.mosaic#457]
Hi,

I was installing the product and, while i was running the bin/buildout i got this error:

`An error occurred when trying to install BTrees 4.4.1. Look above this message for any errors that were output by easy_install.
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Installing recipe plone.recipe.zope2instance.
  Getting distribution for 'BTrees==4.4.1'.
Error: Couldn't install: BTrees 4.4.1
`

Could any one help me?

Thanks everybody! :alien:

**Comment by pfraterdeus** [comment]
Take a look here, maybe it's helpful to you?

https://community.plone.org/t/5-1-5-buildout-chokes-on-extras-require-must-be-a-dictionary-installing-btrees-4-4-1/8185/9

Peter Fraterdeus - @ideaswords (Instagram/Twitter)
--
2020 October Retreat in Bayfield!
MakeaMindfulMark.com
@ideaswords
#emptiness_is_a_design_pattern
