### ISSUE TITLE
Refactor insert menu into e.g. ribbon-like toolbar

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#47]
Something similar to Sea Sprint deco version http://www.screencast.com/t/1BFjd89Xio would be ok, but ribbon-like would probably scale best.

**Comment by agitator** [comment]
+1

**Comment by datakurre** [comment]
@bloodbare @sneridagh @vangheem 

Here's the current Mosaic UI attached, and it's not nice. I'd guess, we should get rid of all the drop down menus and replace them with something more moder and scalable. Personally, I'm been thinking about Office Ribbon toolbar, but couldn't find an existing re-usable implementation of that yet. Any ideas?

![nayttokuva 2015-04-18 kello 16 14 39](https://cloud.githubusercontent.com/assets/160447/7215542/132c2034-e5e6-11e4-9811-50a2e21284bc.png)

Earlier, Ramon committed the default TinyMCE toolbar to be show instead of the custom menu, but that would throw away a lot of Rob's work to make the editor independent from TinyMCE UI and configurable via registry.

So, if you can hint me a nice toolbar JS/CSS -library to use, I could probably adapt it Rob's original design.

**Comment by datakurre** [comment]
@sneridagh @bloodbare What's the easiest way to see all icon-fonts available on Plone 5 by default? What's the best way to extend those to include all icons required for Mosaic toolbar?

**Comment by datakurre** [comment]
I guess, answer to the latter is to create a custom fontello fontset for mosaic.

**Comment by datakurre** [comment]
I tried, if the current toolbar could be refactored as it is, and failed. The code is too much build around for tiles being in optgroup-categorized select-option-menu. I'd guess, here a rewrite would be easier. But on the other hand, the rewrite could start with just implementing the insert-menu as a separate toolbar.

**Comment by datakurre** [comment]
Another try. HTML select/option cannot really be styled, but select2's HTML structure can.

The cleanes solution would be to implement a custom DropdownAdapter for select2, but since it seems to be enough to add two !importants to override the dropdown position (important is needed, because he default DropdownAdapter uses inline style attribute/css for that), I'll experiment with that.

This approach is mostly about select2 and styles and doesn't really need changes into the legacy editor.
 
![nayttokuva 2015-04-26 kello 10 33 11](https://cloud.githubusercontent.com/assets/160447/7336295/bce5bf4e-ebff-11e4-8e08-e888d0efd0fd.png)

**Comment by datakurre** [comment]
This work has now a branch: https://github.com/plone/plone.app.mosaic/tree/datakurre-retoolbar

This will conflict with Ramon's TinyMCE-toolbar related work, because Ramon did not yet push all his changes.

**Comment by gforcada** [comment]
:clap: Great work as usual!

**Comment by datakurre** [comment]
Almost there. Icons and tooltips missing.

![nayttokuva 2015-04-26 kello 17 10 23](https://cloud.githubusercontent.com/assets/160447/7337560/2c55372e-ec37-11e4-9f0c-a4e57949020b.png)

**Comment by saily** [comment]
Stumbled over [oodo](https://demo1.odoo.com) the last days - we could definitely take some ideas from there for our mosaic approach.

**Comment by datakurre** [comment]
@saily Agreed. We looked into oodo at Sorrento, and it's kind of tragic that we've had the backend for similar composition for a long time, but we have only a prototype UI and it's still where it was over five years ago.

A couple of notes:

- Odoo tiles comes with an example content (and many are just HTML-snippets). Yet, that's something we are still missing, so I added an issue https://github.com/plone/plone.app.mosaic/issues/48 I discussed with Ramon about it, and we probably choose plone.resource as a storage backed for those "TTW tiles / template snippets".
 
- I don't remember did you really need to drag tiles from tile bar into content in Odoo. I'd prefer Deco's way where you select the tile with a click and don't need to keep button pressed while dragging.

**Comment by saily** [comment]
damn that i missed it, definitely i need to block time for next year sorrento. 
I just can tell you - from a large international company point of view - they all want those features! And while just reading plone-users with this marketing discussion, this would something we should really push. Great job!

**Comment by agitator** [comment]
Very nice!

**Comment by datakurre** [comment]
Still the hard work of building a custom (fontello) font left.

Yet, for many tiles, there is no recognizable icon available. What would be good enough? Whole name of the tile, or just initials as capitals (and the full name as a tooltip)?

![nayttokuva 2015-04-26 kello 21 13 10](https://cloud.githubusercontent.com/assets/160447/7338601/4c3aa566-ec59-11e4-977a-4bc994346969.png)

**Comment by sneridagh** [comment]
Woot!! Awesome work!!
Indeed, find the right icons is always a hard work. Maybe we can talk with
someone with a designer profile in the community? I'm cc'ing Albert just in
case he has some time to take a look at it.
V.

**Comment by gforcada** [comment]
Cool! We really need a designer to bring the whole concept together and make it shine!

**Comment by djay** [comment]
To be honest I prefered the text version since you are unlikely to have enough meaningful icons to make it memorable so users will mostly endup using tooltips which will be slow. Also I envisage a system where custom tiles will be common (such as from plugins or snippets) and relying heavily on icons will make that even harder to use.

**Comment by datakurre** [comment]
@djay I think, I agree. I need support for icons for format menu, which should look much like TinyMCE toolbar (the original editor had idea of automatically showing buttons only for "favorite" formatting actions and hiding the rest behind dropdown). Yet, for tiles the text columns version might make most sense for now.

**Comment by datakurre** [comment]
Fixed with good enough text-based menus in #49
