### ISSUE TITLE
TTW tiles

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#48]
These would not technically be tiles in p.tiles sense, but more like TTW created and saved HTML snippets (which could contain also pre-confiured transient tiles), which could be dragged into layout similarly to tiles.

But what would be proper storage for these? Probably p.a.registry would be enough? p.resource would be better for large HTML-blobs, but would probably be overkill for the most.

**Comment by djay** [comment]
see discussion from me in https://github.com/plone/plone.app.mosaic/issues/56#issuecomment-98485620 for one idea how this could work.

**Comment by datakurre** [comment]
Simple static HTML tile configuration could be implemented in #61, because the current editor already supports "text tiles with custom default placeholder content".

Smart page template tiles would need a new tile type #56.

**Comment by datakurre** [comment]
Added as fragment tile to collective.themefragments https://github.com/collective/collective.themefragments/commit/1427047a134153c968bee1c2bc120985e72fa585

 - single tile type "Theme fragment"
 - currently allows selecting any theme fragment

Would probably need a way to filter fragments, which should be exposed also as tiles (as a whitelist manifest configuration) and Mosaic should support pre-configured tiles so that one could specify them fragments as individually listed tiles.
