### ISSUE TITLE
Remove the wiki with the roadmap?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.mosaic#502]
This package has a [wiki](https://github.com/plone/plone.app.mosaic/wiki) with a roadmap, as [result from a ticket in 2016](https://github.com/plone/plone.app.mosaic/issues/212#issuecomment-245185415) about maybe including `plone.app.mosaic` in Plone 5 or some later Plone version.

This did not happen in Plone 5. It will not happen in 6.0. I don't think Mosaic will ever end up in core, but feel free to argue otherwise. But the roadmap has some notes on which other packages might be included or merged into other Plone packages. There might still be value in this, but I did not really think about it. The packages involved are pinned in the coredev buildout already.

Having this in a roadmap did not prod anyone into action. Does anyone think items of this roadmap should still happen? If yes, then a PLIP should be started in the `CMFPlone` repository, can easily start as a draft. If not, we might as well close the wiki.

**Comment by mauritsvanrees** [comment]
BTW, this was triggered because the security team got a report from Swapnil Kothawade that the wiki was editable by anyone. I have updated the settings to prevent this. Thanks for your report!

**Comment by jensens** [comment]
Done, I think I created it in 2016. Pointless today.
