### ISSUE TITLE
RichText fields do not save in TinyMCE inline mode.

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.mosaic#503]
I am using Plone 6 b2 with Mosaic as pinned in the official constraints (using plone.app.mosaic 3.0.0a6). 

If I edit any rich text field it does not save it. All input disappears. This was the case in Plone 6 b1 too. 

cc @petschki

**Comment by jensens** [comment]
I found in Firefox inspector, the `id="...-editable "` div appears two times. 
```
<div class="mosaic-tile-content mosaic-rich-text-initialized" data-tileurl="http://localhost:8080/Plone/mosaic/@@plone.app.standardtiles.html/3b72e0e0-a433-4b8f-b7e1-d6e3143cee5a" id="mosaic-rich-text-init-2e900f30-bc9a-46cd-bdb0-980d744ad1bb" style="display: none;"><p>&nbsp;vnmcvnm<br data-mce-bogus="1"></p><p></p></div>
<div id="mosaic-rich-text-init-2e900f30-bc9a-46cd-bdb0-980d744ad1bb-editable"></div>
<div id="mosaic-rich-text-init-2e900f30-bc9a-46cd-bdb0-980d744ad1bb-editable" class="mce-content-body" style="position: relative;" contenteditable="true"></div>
```
Looking at the data send by Mosaic on save, the field was  empty:

```
-----------------------------75732121922458411173795644499
Content-Disposition: form-data; name="form.widgets.IDublinCore.title"

Mosaic
-----------------------------75732121922458411173795644499
Content-Disposition: form-data; name="form.widgets.IDublinCore.description"

dfythh
-----------------------------75732121922458411173795644499
Content-Disposition: form-data; name="form.widgets.IRichTextBehavior.text"


-----------------------------75732121922458411173795644499
Content-Disposition: form-data; name="id9b9a-editable"


-----------------------------75732121922458411173795644499
Content-Disposition: form-data; name="form.widgets.IRichTextBehavior.text.mimeType"

text/html
-----------------------------75732121922458411173795644499
```

Also, I have no idea what `id9b9a-editable` is good for.

**Comment by petschki** [comment]
Hm strange. I'm not able to reproduce this. It's definitifely wrong, that there are sibling nodes with `id="...-editable"` there. I do not have them. If I create a mosaic page from scratch with "title, description, text" as layout, enter a text and save it it works. The DOM from the RichText behavior looks like this:

<img width="751" alt="Bildschirmfoto 2022-09-13 um 07 33 56" src="https://user-images.githubusercontent.com/511761/189817519-c62c9acd-91e4-4542-bafb-fa485296ae71.png">

Does this happen with the RichTextBehavior field or plone.app.standardtiles.html? If using both on the page the DOM should look like this:

<img width="2311" alt="Bildschirmfoto 2022-09-13 um 07 40 17" src="https://user-images.githubusercontent.com/511761/189818449-0b89bd4f-aa0d-498c-a758-899d67b8c514.png">

**Comment by jensens** [comment]
In my setup I globally configured TinyMCE to run in Inline-Mode (TinyMCE controlpanel settings `Run TinyMCE in inline mode.`)
If I uncheck the box all works as expected

**Comment by petschki** [comment]
ah ... now the same happens here too.

**Comment by jensens** [comment]
Any idea how to fix it? I need both, inline editor in mosaic and on normal pages.

**Comment by petschki** [comment]
must be some tweaks here in `saveForm()` for the RichTextBehavior https://github.com/plone/plone.app.mosaic/blob/master/resources/js/mosaic.tile.js#L892 and in `setupWysiwyg()` https://github.com/plone/plone.app.mosaic/blob/master/resources/js/mosaic.tile.js#L941 but this is strange, since the `inline` parameter is always set to `True` for rich text tiles.

I currently have no time to take a look at that, but will be available at the conference sprint.
