### ISSUE TITLE
Cannot have more than 1 RichText tile in a mosaic page

### ISSUE THREAD

**Issue by frapell** [plone/plone.app.mosaic#511]
I've been fighting this issue for a couple of days and cannot figure it out...
Steps to reproduce:

1. Create a site from scratch
2. Install Mosaic
3. Create a test page
4. Assign the `Mosaic Layout`
5. Edit -> Customize -> Add 3 "Rich Text" tiles
6. Save page
7. Edit the page again

On step 5, all 3 rich text tiles are editable, however, after re-editing the page, only 1 can be edited.

* Mosaic 3.0.0b2
* Plone 6.0.0rc2 (6010)
* CMF 2.6.0
* Zope 5.7
* Python 3.10.6 (main, Nov 2 2022, 18:53:38) [GCC 11.3.0]
* PIL 9.3.0 (Pillow)
* WSGI: On
* Server: waitress 2.1.2

**Comment by petschki** [comment]
I could not reproduce this here. Same versions. Do you have an info/error in the JS console?
I assum, you have checked our mosaic on master because of version 3.0.0b2 ... but thats the same here.

**Comment by frapell** [comment]
@petschki Oh wow, that's so weird... I've recorded a quick screencast showing the issue on my side, is this not happening for you at all?
https://youtu.be/HXWBQwPtMVg

Also, I've noticed for quite some time that the Lorem Ipsum text that comes with the tile gets deleted when placing the tile, which has been happening for quite some time, but not sure if it is an indication of something not working fine

**Comment by frapell** [comment]
I think this is no Mosaic bug, but instead in Mockup. Created a ticket over there, and closing this
