### ISSUE TITLE
Problems with Zope 5.7.3 ?!

### ISSUE THREAD

**Issue by krissik** [plone/plone.app.mosaic#516]
I'm testing Plone6 Classic. After an update from Zope 5.7 to 5.7.3 plone.app.mosaic stopped working. A document with mosaic layout  now returns html code (see screenshot).
If I pin Zope to 5.7 it works again. The Changelog of [5.7.1](https://github.com/zopefoundation/Zope/blob/master/CHANGES.rst#571-2022-12-16) says "Set the published default Content-Type header to text/plain". I guess it might have something to do with it ...?

![zope5-7-3](https://user-images.githubusercontent.com/5301889/208697937-29515cbb-79a7-452d-8478-11fef0c3fd89.png)

**Comment by mauritsvanrees** [comment]
Confirmed. I think I have a fix in `plone.app.blocks`. I will make a PR.

**Comment by mauritsvanrees** [comment]
I have made PRs. For Plone 6 you may want to try this one:
https://github.com/plone/plone.app.blocks/pull/102

**Comment by krissik** [comment]
It is working - Thank you!

**Comment by mauritsvanrees** [comment]
Fix released in `plone.app.blocks` 5.2.1, 6.0.2, and 7.0.0.

**Comment by petschki** [comment]
so this can be closed right? If I'm wrong please reopen
