### ISSUE TITLE
Some tiles should not be editable

### ISSUE THREAD

**Issue by frapell** [plone/plone.app.mosaic#517]
There are a few tiles coming from `plone.app.standardtiles` that should not have the "Edit" button, since they are simply rendering viewlets and they have nothing to edit, showing an empty edit screen, confusing users. These are:

* Discussion
* Document byline
* Related Items
* Keywords

**Comment by petschki** [comment]
Shouldn't `related items` and `keywords` show the input widget from the `EditForm` when hittin the edit button? At least thats what I would expect ...

**Comment by jensens** [comment]
I think we merge PR #518 and then add new issue can be added to fix the missing edit forms?

**Comment by frapell** [comment]
@jensens Yeah, I agree ( I don't think I'll have the time soon to implement the edit forms myself, though...)
