### ISSUE TITLE
Tiles should have defaults so that new tiles could be placed without manually filling their add form

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#52]
Wouldn't it be nice, if we could add new tiles just with a single click to see how they look like and only configure them later.

This would be possible by simply adding working default values for every required tile field, and auto-submit the tile add form, when it seems to have all required fields filled (with those defaults).

It that auto-check is trivial, this only needs some code into the layout (editor) pattern and, of course, those defaults into plone.app.standardtiles.

**Comment by agitator** [comment]
+1

**Comment by simahawk** [comment]
+1

**Comment by datakurre** [comment]
Fixed in https://github.com/plone/plone.app.mosaic/pull/71
