### ISSUE TITLE
Mosaic editor is not working

### ISSUE THREAD

**Issue by mck9** [plone/plone.app.mosaic#524]
I installed plone.app.mosaic 3.0.1 in a fresh plone 6.0.2 site. After switching the view to "mosaic layout" and clicking "edit" the mosaic editor does not show up.

How to fix/debug the issue?

**Comment by petschki** [comment]
Is there a JS error on the browser console?

**Comment by mck9** [comment]
No, there isn't. I also tried it in firefox and chromium.

**Comment by petschki** [comment]
I tried it just now, and got this screen. The layout selection modal is far too right but the pattern works in a fresh installation.

<img width="1665" alt="Bildschirm­foto 2023-02-28 um 10 57 21" src="https://user-images.githubusercontent.com/511761/221818881-00d0b519-3671-4f09-8fef-7c38716696a6.png">

**Comment by petschki** [comment]
You could debug the issue by checking out mosaic and running the resources with webpack as described here: https://github.com/plone/plone.app.mosaic/blob/master/DEVELOPMENT.rst ... if there's no modal loading on initial editing the page, it's likely a JS resource problem.

**Comment by mck9** [comment]
Super strange. I restarted the server, and now it works.

To reproduce the issue: I created a new Plone site and added mosaic. The mosaic editor shows up only after restarting plone.

**Comment by petschki** [comment]
Sounds like a resource registries caching problem. I remember having this also some time ago with a custom addon with resources. And there was an issue about that: https://github.com/plone/Products.CMFPlone/issues/3505

**Comment by mauritsvanrees** [comment]
The resource registries caching problem that needs a restart should be solved with the upcoming Plone 6.0.4.
See https://github.com/plone/Products.CMFPlone/pull/3771
