### ISSUE TITLE
Split "Text" tile into multiple "most usual text content" tiles

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#53]
I propose that instead of "Text" tile (under "Structure" tiles) we should have multiple tiles for the most usual use-cases:

* heading
* subheading
* paragraph
* bulleted list
* numbered list

Would these be enough? "Table" would be nice, but that would require more work than these would.

Technically these would all be "Text" tiles, but with different example content.

Also, this would encourage users to think their content as multiple "blocks" instead of single Word  document dump.

**Comment by gforcada** [comment]
:+1: this should then be customizable on a policy package while at der Freitag for example we would have quite a lot more tiles like that, whereas on other websites maybe heading, paragraph and bulleted lists would be enough

**Comment by datakurre** [comment]
Oh dear, this was already implemented by Rob :+)

It's even so that you can filter available TinyMCE formatting actions per tile type so that you can really have a "Heading"-tile, which only allows different levels of heading as formatting actions.

So, this issue only needs to implement nice defaults.

Would my original list be ok?

**Comment by gforcada** [comment]
Yes, the original list makes sense, I would rather keep it short and simple (but functional) than bloated and sort-of-works :)

**Comment by datakurre** [comment]
![textiles](https://cloud.githubusercontent.com/assets/160447/7547695/df0c287e-f5fa-11e4-8df4-9c9413fd47b4.gif)

**Comment by datakurre** [comment]
If these end up being a bad idea, it should be pretty easy to remove them from the default registry.xml.

**Comment by gforcada** [comment]
Awesome! :tada:
