### ISSUE TITLE
Mosaic view broken?

### ISSUE THREAD

**Issue by thet** [plone/plone.app.mosaic#536]
In 6.0.x coredev buildout with plone.app.mosaic - so also with CMFPlone master - i get the following when creating a mosaic page:

![Screenshot from 2023-04-21 13-49-24](https://user-images.githubusercontent.com/170891/233629879-be815c5d-179e-4cab-9236-af27baff2735.png)

When i manually add `@@edit` to the url I‌ get the editor, but incorrectly styled:

![Screenshot from 2023-04-21 13-49-41](https://user-images.githubusercontent.com/170891/233630011-ed1f61f6-c028-485e-a457-e131ab2b44b0.png)

When I open the inspector it's styled correctly (maybe due to the layout change. but directly opening the edit view with an open inspector also gives me the correct styling):

![Screenshot from 2023-04-21 13-50-12](https://user-images.githubusercontent.com/170891/233630206-78d38f31-d9fe-46af-859a-5b6e0c01f143.png)

Can anyone confirm?

I did not yet investigate the broken layout view, but this would be a blocker for something.

not sure if that is related to: https://github.com/plone/plone.app.mosaic/issues/524
is it @mck9 ?

**Comment by mck9** [comment]
@thet I don't think so. in #524 I didn't get the mosaic editor, only the standard edit form.

**Comment by fredvd** [comment]
@thet the #524 issue will be solved in Plone 6.0.4.   The problem there is that the resource registry output is cached and wasn't purged when a new add'on (like Mosaic) registered its needed resources.  

I also remember seeing a PR or mention by someone that fixed the template selection modal when editing a new layout for the first time, I experienced it myself as well that the modal is moved to the right off screen. But I can't find the mention/fix anymore.

**Comment by frapell** [comment]
@thet yeah, the plain-text view when selecting a mosaic layout was fixed in https://github.com/plone/plone.app.blocks/issues/101 you need to pin `plone.app.blocks` to 7.0.0 or newer

**Comment by thet** [comment]
That should then go into the ecosystem version sections of Plone 5.2, 6.0 and 6.1

**Comment by mauritsvanrees** [comment]
The correct version of `plone.app.blocks` is already pinned in Plone 5.2.10.2 and 6.0.0.2.
Note that in Plone 6.0 when using buildout in your project you need to explicitly also extend `versions-ecosystem.cfg`.

**Comment by thet** [comment]
@frapell my bad. I had it pinned locally to a 6.x version :roll_eyes: 
fixed :)

**Comment by petschki** [comment]
Note: I took a look at the broken layout editor overlay and fixed it locally. I'll prepare a PR with that ... and another issue which I found out using custom layouts.
