### ISSUE TITLE
Index layout into SearchableText index

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#54]
Should this be in plone.app.blocks (with the layout behavior) or in Mosaic?

Technically this should be optional and active only when collective.dexteritytextindexer is available (and the behavior enabled for the content type).

Otherwise this should be quite trivial: layout field should have a such adapter for dexteritytextindexershould, which transforms the layout into plain/text for indexing. This would be enough to index all the text tile contents (which are saved as such into layout HTML).

**Comment by datakurre** [comment]
Fixed in p.a.blocks 2.1.0 with https://github.com/plone/plone.app.blocks/commit/d6cbc0a8c1689336332b61d376b3e7f205a68de8

**Comment by datakurre** [comment]
How to enable:
- add collective.dexteritytextindexer into buildout
- enable Dynamic SearchableText indexer behavior for your content type

**Comment by gforcada** [comment]
Cool!
