### ISSUE TITLE
Editor should be able to add padding "between tiles"

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#55]
Yet, I have no idea, how this should be implemented (from UI point of view and from technical/DOM/CSS  point of view).

**Comment by gforcada** [comment]
Wouldn't be an option to create space tiles? So tiles which are empty on content but just have a customizable width/height?

Although how that should play with responsive design?

**Comment by simahawk** [comment]
I think having style settings on tiles themselves would be better. When you hover a tile you get the "i" icon for editing tile settings (not intuitive though): we can add a style settings icon beside it that opens a popup with predefined settings to select or apply specific width/height/padding.

**Comment by datakurre** [comment]
This appears to be almost possible by now.

We could have a either a completely new dropdown menu for "styles" or 
add them as a new category into "format" menu. The only downside is that 
users could confuse them with RichText formatting.

The "format" menu already has a few similar actions "Tile block", "Tile 
left", "Tile Right".

Next, we have could a new generic actions: "Toggle style"

         $.mosaic.registerAction('toggle-style', {
             exec: function () {
                 $(".mosaic-selected-tile", $.mosaic.document)
                     .toggleClass(arguments[0].value);
             }
         });

that could be re-used with a convention that the action name is applied 
as a toggled style

   <records interface="plone.app.mosaic.interfaces.IWeightedDict"
            prefix="plone.app.mosaic.format_categories.styles">
     <value key="name">styles</value>
     <value key="label">Styles</value>
     <value key="weight">60</value>
   </records>

   <records interface="plone.app.mosaic.interfaces.IFormat"
            prefix="plone.app.mosaic.formats.my_unique_style_action_id">
     <value key="name">MyCustomStyleClass</value>
     <value key="category">styles</value>
     <value key="label">My Custom Style</value>
     <value key="action">apply-style</value>
     <value key="icon">true</value>
     <value key="favorite">false</value>
     <value key="weight">160</value>
   </records>

Or maybe even smarter, if someone figures out a better way. Especially 
the javascript part should probably be able to replace the existing 
style with the new one instead of just toggling.

(The example above would insert these styles into a new category into 
format menu.)

**Comment by datakurre** [comment]
So, we can do styles, but should we also do padding? It can do similarly by adding new formatting actions like "Tile padding left", "Tile padding right", but what should those actions really be - taken account that they may not ask parameters from the user. Or should they? (I think, we don't have JS-only dialogs available...)

**Comment by datakurre** [comment]
The easiest padding solution, I can think of, would be new formatting actions

- Increase tile padding [adds padding-right and padding-bottom]
- Decrease tile padding [removes padding-right and padding-bottom]

Or maybe "Tile padding" category under "Format menu":

- More left padding / Left padding + / Left +
- Less left padding / Left padding – / Left –
- More bottom padding / Bottom padding + / Bottom +
- Less bottom padding / Bottom padding – / Bottom –

I know that many would prefer some interactive dialog, but it these could be implemented as simple actions, they could also have configurable keybindings.

**Comment by datakurre** [comment]
One more option. Since this can be customized for client projects, we only need to have something simple and easy OOTB. How about just one action

- Padding

which would rotate by adding and removing padding so that

- 1 clicks -> padding left
- 2 clicks -> padding left + bottom 
- ...
- 4 clicks -> padding left + bottom + right + top
- 5 clicks -> padding bottom + right + top
- 9 clicks -> no padding

Similar action could be done to add simple hairline border.

**Comment by djay** [comment]
Is there a concept of custom tile styles? Then you give the control to the
theme to define several options for padding and other things like borders
etc. This means a more rigid theme could prevent padding that makes the
page look bad.

**Comment by datakurre** [comment]
Styles were discussed earlier in this issue. So, maybe styles should be the way to implement this. I could add them into format-menu at first and implement a few default styles to allow enough padding options to make Mosaic pages look better OOTB.

**Comment by agitator** [comment]
I would rather have a style "menu" for each tile, to be able to select some additional formatting in a reproduceable way. 

If it's just about padding and borders, maybe something similar to the firefox box model overview could make sense.
![screen shot 2015-05-03 at 11 04 52](https://cloud.githubusercontent.com/assets/365761/7444460/6763d38c-f184-11e4-901f-cc7b509af066.png)

**Comment by datakurre** [comment]
Oh, dear. Now this must be delayed until we find out some compromise.

Personally, originally I prefered more direct manipulation to empower editors, but "box model overview" feels like too much micromanagement. On the other hand, I understand @djay's and @simahawk's view that this is more of a theming issue and styles are the only sane way to keep the content uniform and theme updateable. I'm leaning towards styles...

About @gforcada's proposal. Spacing tiles (besided causing extra markup into HTML) would work vertically, but would not work horizontally because of Mosaic relies on some grid system and minimum width for a tile is a single unit in the used grid system.

**Comment by agitator** [comment]
+1 for the style solution

**Comment by datakurre** [comment]
![nayttokuva 2015-05-06 kello 22 00 46](https://cloud.githubusercontent.com/assets/160447/7501295/a9d125a8-f43b-11e4-8600-20a935cbef9c.png)

**Comment by djay** [comment]
Everything on that menu is a style. Those styles apply to the entire tile
so.maybe should be called "tile style" and perhaps put on the left or right
to help indicate its different.
Also these tile styles work on all tile types right?

**Comment by datakurre** [comment]
![nayttokuva 2015-05-07 kello 7 37 31](https://cloud.githubusercontent.com/assets/160447/7508631/2f497ec4-f48c-11e4-947a-11c3f674153a.png)

**Comment by datakurre** [comment]
![nayttokuva 2015-05-07 kello 9 22 15](https://cloud.githubusercontent.com/assets/160447/7509573/ff06f930-f49a-11e4-92a8-4b757084e12b.png)

**Comment by datakurre** [comment]
![nayttokuva 2015-05-07 kello 9 26 25](https://cloud.githubusercontent.com/assets/160447/7509582/2e35407c-f49b-11e4-9387-91fdf364203d.png)

**Comment by djay** [comment]
+1 esp if thats on every tile.

**Comment by djay** [comment]
How does someone add a new custom style to appear in those lists?

As previously stated it would be really really nice if you can do it directly inside the theme since thats where the css has to live anyway for a custom styles. The registry is not a great place due to syncing issues. you uninstall a theme and install another one with different styles then the user has options in the menu that no longer work and may not understand why.

**Comment by datakurre** [comment]
@djay Everything is configurable through registry. That configuration comes all the way from the original Deco editor. Each tile (besides generated field tiles) have its own configuration, where each tile can have different actions (or use similarly configured set of default actions).

So, currently configuration in theme requires c.themesitesetup and registry.xml. To make it easier, I would not implement another configuration place, but enhance registry so that it's easier to add and remove theme specific changes. E.g. some kind of layers and/or easier configuration using yaml or better syntax (ini is probably too simple for complex registry entries; json is too syntax error prone).

**Comment by djay** [comment]
Just noticed how squarespace do it using comments in css/less. I think thats a really nice idea.

http://developers.squarespace.com/style-editor/

**Comment by simahawk** [comment]
@djay nice solution indeed. It allows you to tie the style w/ what you see from the editor, and not need to register any other thing.
