### ISSUE TITLE
Always disable layout view on add-form

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.mosaic#581]
I have created [`collective.mosaicpage`](https://github.com/collective/collective.mosaicpage).  This adds a portal_type that has `layout_view` as default_view and as only allowed view.
In a standard Plone site with Mosaic you can achieve almost the same by editing the Document type to only have `layout_view`.

Problem: when adding such a page, you do not get the normal content edit screen so you can set a title and description, but you get the Mosaic layout editor: choose a layout, add tiles.  Here the Save and Cancel buttons do not work.

In https://github.com/collective/collective.mosaicpage/pull/2, specifically [this commit](https://github.com/collective/collective.mosaicpage/pull/2/commits/559479637d1395630a9631ef0ae8ea9cf842f9a5), I patch the layout view to not be enabled on the add-form.
I would like to make a PR to do this in Mosaic itself, in [`widget.py`](https://github.com/plone/plone.app.mosaic/blob/9a7df8a0bb25ff3a4a9da3fc818731f27c1349c8/src/plone/app/mosaic/widget.py#L55-L62).

Before I do that, I wonder: is there ever a situation where we want to immediately see the layout view when adding a content item?

**Comment by fredvd** [comment]
@mauritsvanrees with "you do not get the normal content edit screen" you mean the modal where you can select one of the available content layouts?  (by default 2 layouts, title+description, or title, description,richtext).   

I can imagine that if you create a new contenttype where you want to have a predefined layout, that it should be possible to couple contenttype to layout and skip the layout selection modal?

plone.volto has a similar feature where you can define an existing block layout and connect it to content type as the default 'pre filled' layout using the contenttype control panel.

**Comment by mauritsvanrees** [comment]
On the add-form I want to have the normal content edit screen that you get in a standard Classic Plone site without Mosaic, so you can set all the fields: title, description, dates, tags, etc.

What I get, is the layout view:

* The modal to select a content layout. If only one such layout is defined for the portal_type, this modal is skipped.
* Afterwards the real layout view where you can add tiles.  Here the Save button does nothing.

If the layout view could be fixed so it also works on an add-form, so that clicking the Save button actually creates the content item and the tiles, that would be fine too.  No idea if this is a five minute fix or a five day fix. :-)

**Comment by petschki** [comment]
I get the idea ... two thoughts about this:

1. Mosaic has a condition for AddForm view here https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/browser/main_template.py#L242 maybe you can override this `MainTemplateBrowserView` with your addon browserlayer and do some logic there to disable pattern initialization.

2. Mosaic gets enabled on the https://github.com/plone/plone.app.blocks/blob/master/plone/app/blocks/layoutbehavior.py fields, so if those fields are missing on the add-form this should do the trick too ...

**Comment by mauritsvanrees** [comment]
I have tried the suggestions, but I could not get them to work for my use case.  I will keep it to the patch I had already in `collective.mosaicpage`.
