### ISSUE TITLE
customized tinyMCE buttons on Rich Text tiles after update to 3.1.4

### ISSUE THREAD

**Issue by krissik** [plone/plone.app.mosaic#582]
We have customized tinyMCE buttons for html tiles as described here

https://github.com/plone/plone.app.mosaic/blob/9a7df8a0bb25ff3a4a9da3fc818731f27c1349c8/docs/rich_text_buttons.rst

After Plone Update from 5.2 to 6.0.6 - and so updating plone.app.mosaic from 2.2.5 -> 3.1.4 - this is not working anymore. The buttons that are globally configured for tinyMCE (registry key: `plone.toolbar`) are shown on html tiles too.

Is this by intention, a bug or did I miss some new configuration?

**Comment by petschki** [comment]
This was mainly decided by me in order to generalize the usage of TinyMCE control panel also for mosaic toolbar.
But working a while with this I'm now convinced, that a separate toolbar config for mosaic editor makes sense.

/cc @frapell

**Comment by frapell** [comment]
@petschki Yeah, I agree... is this change easily reverted?

**Comment by petschki** [comment]
I've refactored and implemented the toolbar customization again. Since we're reusing `pat-tinymce` now we can simply override the tiny pattern config in the widget code. See #584

**Comment by petschki** [comment]
Fixed and released in `3.1.5`
