### ISSUE TITLE
use plone.api

### ISSUE THREAD

**Issue by simahawk** [plone/plone.app.mosaic#59]
and replace all `getToolByName` and other stuff.

**Comment by gforcada** [comment]
:+1:

**Comment by datakurre** [comment]
@gforcada Do we already have check for that in p.r.codeanalysis? :+)

**Comment by gforcada** [comment]
@tisto still not, but that would be a nice addition indeed. I will add that as an issue :)

**Comment by gforcada** [comment]
Submitted as https://github.com/plone/plone.recipe.codeanalysis/issues/118
