### ISSUE TITLE
Remove broken or unstable tiles from default configuration

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#73]
* [x] Exclude from navigation should be hidden from field tiles (blacklist in registry.xml)
* [x] Change note should be hidden from field tiles (blacklist in registry.xml)
* [x] Table of contents note should be hidden from field tiles (blacklist in registry.xml) in favor of Table of contents stdtile
* [x] Related items should be hidden from field tiles (blacklist in registry.xml) in favor of Related items stdtile (or should it be? which one is better)
* [x] Calendar tile should probably be removed (or fixed)
* [x] Discussion tile should be tested

**Comment by datakurre** [comment]
https://github.com/plone/plone.app.mosaic/commit/2dec02cbc5456cde547829870146ea358568dc55
https://github.com/plone/plone.app.mosaic/commit/f63cb9b30bd663416d552558474ac9b64a783a2c

**Comment by datakurre** [comment]
![mosaic-editor-select-field-text-tile](https://cloud.githubusercontent.com/assets/160447/7549345/3cc99b8e-f639-11e4-9049-a6d7ef282b05.png)

**Comment by datakurre** [comment]
DiscussionTile fixed in https://github.com/plone/plone.app.standardtiles/commit/8de2dccef59c78e4a716cc38f449eb7edd134e19

**Comment by datakurre** [comment]
Portlet tile remains a bit broken. I'm creating issues from the remaining tiles soonish.

**Comment by datakurre** [comment]
@thet @frapell @jcbrand About Plone modal pattern. Is it possible to configure modal to close itself when Cancel-button form the modal form is pressed? If so, how? (By default, the modal submits the cancel button and it can be only closed after that in formActionSuccess.)

**Comment by frapell** [comment]
@datakurre You can override the actions by default. I haven't tested it, but it should be something like:

<a href="#" class="pat-modal" data-pat-modal='{"actions": { "#form-buttons-cancel": { "modalFunction": "hide" }}}' />

You may need to set automaticallyAddButtonActions: false so the cancel doesn't end up with default event as well, in which case, you will need to manually set the action for save.

More info in http://plone.github.io/mockup/dev/#pattern/modal

**Comment by datakurre** [comment]
@frapell Thanks. Since ``automaticallyAddButtonActions: false`` would have required to manually wire Save and other buttons, I ended up just re-wiring Cancel-buttons manually after ``after-render`` event.
