### ISSUE TITLE
Attachments tiles should be transient or available only when on edit form

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#75]
@bloodbare I recall, that you had some generic "upload temporary files" idea for fixing Image tile. Would that be usable to make also attachment tile transient? It's probably the last persistent tile after Image tile.

**Comment by djay** [comment]
Personally I think image tile and files should just get uploaded to the
current folder (or where they pick) rather than this media folder idea. If
we go to folderish pages this becomes less messy anyway. But it should
support a single folder for images if that is all that's available.

**Comment by datakurre** [comment]
Then, of course, we still have the option of plone.app.drafts (and keeping persistent tiles). Server side drafting feels a bit oldschool, but it has been working and can be fixed to work again.

**Comment by datakurre** [comment]
@bloodbare @gforcada Any ideas for these remaining persistent tiles? (Attachments and Images)

Or I reintroduce dependenc on plone.app.drafts, which I have now working with DX and Mosaic.

**Comment by datakurre** [comment]
Drafting looks promising and brings also required auto-save. I'll merge it soon https://github.com/plone/plone.app.mosaic/pull/79 so a few persistent tiles will be allowed.

I've fixed attachment tile to store blobs and work on Plone 5.
