### ISSUE TITLE
Available portlets in portlet tiles should be limited

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#76]
https://github.com/plone/plone.app.mosaic/commit/c99fce2d8e871cc7b13efd882b132492554eb407 restored support for portlet tiles in the current Mosaic master. And I also did some commits to stdtiles to fix a few generic issues with portlet tiles.

I'm now able to add and edit all the default portlets as tiles, but

* some portlets (e.g. navigation) have widgets with legacy AJAX -features, which cannot be fixed to work nicely with the mockup modal (modal selectors should be fixed to include widget's buttons, but then the buttons would go into bottom of the modal, which is not usable)

* most (if not all) of the default portlets can be replaced with the current stdtiles (content listing tile is very powerful)

* calendar portlet's month navigation does not work

I think, we need to be able to blacklist "bad portlets" to make the portlets tile useful.

@simahawk Since you are the orginal author of the portlet tile, would you be able to work on that? Also, we have the issue of portletmanager being visible in Plone 5 toolbar. If these don't get fixed, we should disable the portlet tile by default (and possibly leave the custom portletmanager uninstalled).

All the others: What do you think about the portlet tile? Personally, I'm a bit afraid of the persistent portlet manager it requires and how easy it is to get junk into it (add portlet in Mosaic Layout, but then leave form without saving and the persistent portlet assignment is never deleted).

**Comment by simahawk** [comment]
@datakurre I think I can work on that. As for being afraid: yes, that could happen :)
About leaving the form: is there a good way to hook custom actions to "cancel" button (or any other closing action)?

**Comment by datakurre** [comment]
@simahawk The simplest way to both use mockup modal's default form action bindings and have a custom binding for cancel is the one in the commit referred earlier. (Modal does not have options for that.)

**Comment by datakurre** [comment]
@simahawk Oh, sorry. I didn't understood correctly.

I think, mosaic.actions.js has cancel action and that could be made hookable. Yet, it still won't work, if you just close the browser.

**Comment by datakurre** [comment]
@simahawk Maybe better to avoid the issue of dangling portlets for now and just implement the available portlets filter. I'd prefer to make portlets tile disabled by default in Mosaic, but let it be there (with sane default available set) for those, who know what they are doing.

I looked recently into p.a.drafts again, and I believe that the issue of dangling tiles could be fixed with p.a.drafts support (it would require refreshing p.a.drafts, refreshing and merging plone.app.z3cformdrafts into p.a.drafts, and probably some small integration code into p.a.tiles, stdtiles and Mosaic). Yet, it would be so much work, that focusing making as many tiles transient as possible, would be better way to spend time.

(Another problem with p.a.drafts is that server side drafting is really outdated and maybe possible time in the future should be used to implement client side drafting instead.)

**Comment by datakurre** [comment]
@simahawk I disabled portlet tile for now, so we don't focus more of our limited resources for it. The portlet tile itself works (if someone would like to enabled it) thanks to all work done into plone.app.tiles and plone.app.standardtiles, but its lifecycle need more thinking. For example, now with plone.app.drafts, adding and deleting portlets should work lazily with drafting, which is not trivial. (Drafting handles regular persistent tile annotations, but does not know anything about portlet managers.)

**Comment by djay** [comment]
@datakurre How does one enable a tile like the viewletmanager tile? It's not at all obvious :(

**Comment by datakurre** [comment]
Agreed. Some tiles, including viewletmanager were designed to be used only in ”site layouts” and user story on those is not complete. (There is no layout editor for site layouts.) In site layouts it’s just ``data-tile=”./@@plone.app.standardtiles.viewletmanager?manager=plone.beforecontent”``. I believe that was covered in Jens’ PloneConf talk about site layouts.
