### ISSUE TITLE
Can't `Save` the custom layout in Chrome

### ISSUE THREAD

**Issue by ivanteoh** [plone/plone.app.mosaic#78]
After finished editing the custom layout and click `save` button, the changes are not saved in Plone 4.3.

**Comment by datakurre** [comment]
@ivanteoh Which browser? Does the ``save`` button still return you to the view mode or does it just do nothing at all?

If it does nothing, there's probably some JavaScript error. If possible, please try to repeat with browser developer console open and report the error.

**Comment by datakurre** [comment]
Cannot reproduce with Firefox.

**Comment by ivanteoh** [comment]
Just verified. It works with Firefox but not Chrome.

**Comment by datakurre** [comment]
@ivanteoh Which Chrome version? I remember seeing similar issues with Chrome, but now when I test this with Chrome 36.0.1985.143 on OSX, everything works. (There are few warnings and 404 errors due tue issues in plone.app.widgets, but nothing else.)

**Comment by datakurre** [comment]
I seemed to had a very old version. Now my Chrome update to 42.0.2311.152 (64-bit), but everything seems to still work.

**Comment by ivanteoh** [comment]
I have the same Chrome version 42.0.2311.152 (64-bit). I will verify again when I am at home.

**Comment by datakurre** [comment]
I recall, that logged error kind of eat the original error message, but one could try to ease debugging with:

1. replacing extras/plone.app.widgets/plone/app/widgets/static/widgets.min.js with non-minified extras/plone.app.widgets/plone/app/widgets/static/widgets.js

2. build non-minified version of mosaic bundle with 

    npm install
    bower install
    make clean all

(expects nodejs, with globally installed npm and bower)

**Comment by ivanteoh** [comment]
After I followed your step 1 and step 2 on previous comments, I can `save` the custom layout now in Chrome. Do you know what's wrong?

**Comment by datakurre** [comment]
I'm sorry, but I don't know, what could be the reason.

Can you still reproduce this issue? Checkout original versions and cannot save? Then do step1 and try again, and only then step 2, and try again. Just to try to frame the issue better. And just in case, for each try, use a new private browsing windoe so that nothing comes from the browser cache for sure.

**Comment by ivanteoh** [comment]
I start all over again. I remove the original folder and execute the steps below and this time it is working now in both Chrome and Firefox. I think it is no longer an issue. It could be me was messing around the code.

```
$ git clone git@github.com:plone/plone.app.mosaic.git
$ cd plone.app.mosaic
$ pyenv activate venvmosaic
$ python bootstrap.py
$ ./bin/buildout -N
$ ./bin/instance fg
# click `Create a new Plone site`
# Enter `User Name` and `Password`
# Select `Plone Mosaic for Plone 4`
# Click `Create Plone Site` button
# At http://localhost:8080/Plone, select `Custom layout` for `Display`
# Click `Edit`
# Selct `Insert > Structure > Text`
# Drag the text below the description.
# Click `Save`
```
