### ISSUE TITLE
Release Plone Mosaic 1.0a1

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#81]
What do you think about making alpha release now that things mostly work, before anyone starts to refactor something too much again? :+)

We need new releases for the whole stack:

* [x] plone.app.blocks (2.1.0)
* [x] plone.tiles (1.4.0)
* [x] plone.app.tiles (2.1.0)
* [x] plone.app.drafts (1.0b1)
* [x] plone.app.standardtiles (1.0a1)

and then pin minimum required versions (and provide a KGS versions.cfg) for

* [x] plone.app.mosaic (1.0a1)

the current version still works for both Plone 4.3.x and Plone 5:

* http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/361/361.1/getting-started.html#mosaic-editor
* http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/361/361.2/getting-started.html#mosaic-editor

**Comment by gforcada** [comment]
:+1: let's get the ball rolling and make it easier for everyone to test! :)

**Comment by datakurre** [comment]
@esteele Hi, Eric. Would you be able to help us with Mosaic alpha release and make releases for the following packages (with to be released versions):

* [ ] plone.app.blocks (2.1.0)
* [ ] plone.tiles (1.4.0)
* [ ] plone.app.tiles (2.1.0)
* [ ] plone.app.drafts (1.0b1)
* [ ] plone.app.standardtiles (1.0a1)

I think, they have correct versions in setup.py, manifest in place and changelog updated.

I could then check tha everything works and make Mosaic release (and then give you its PyPI ownership).

**Comment by datakurre** [comment]
@thet How about plone.app.widgets 1.8.0? That would make Plone Mosaic 1.0a1 also work on Plone 4.3.x.

**Comment by simahawk** [comment]
GO! GO! GO! :+1:

**Comment by esteele** [comment]
Sure. I'll work on those this evening.

**Comment by datakurre** [comment]
@esteele Thanks!

**Comment by datakurre** [comment]
@esteele Let's delay the release. I had too much testing and found a drafting related issue, which I'd like to fix. I ping here when ready.

**Comment by datakurre** [comment]
@esteele Ok. Fixed. You are free to do the releases (expect for p.a.mosaic) when you have time :)

**Comment by esteele** [comment]
Made releases of plone.app.blocks, plone.tiles, and plone.app.tiles. I'll need to get pypi rights for plone.app.drafts from @optilude

**Comment by datakurre** [comment]
@esteele Thanks. It seems stdtiles has not had any release, so I can release it, once drafts is released.

**Comment by datakurre** [comment]
@esteele I released plone.app.standardtiles and gave also you and plone the ownership.

**Comment by datakurre** [comment]
Done. Thanks @esteele for help.

https://community.plone.org/t/plone-mosaic-1-0a1-released/683

plone.app.standardtiles went up to 1.0a3, because of a small template fix and a small fix for Plone 4.3 support (even nobody else cares)

**Comment by gforcada** [comment]
:+1: !!

**Comment by datakurre** [comment]
Forgot to thank @thet for p.a.widgets 1.8.0 to make this work even on Plone 4.3.x.

**Comment by thet** [comment]
You're very  welcome
