### ISSUE TITLE
Tile for visual elements / mockup patterns

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#97]
There should be a tile for integrating visual (bootstrap) elements like tabs, accordion. Maybe a generic tile for mockup patterns?

**Comment by datakurre** [comment]
Agreed. More generally, there should be an easy way to add new HTML tiles. Theres already support for that, but no configuration panel to define new tiles.

Tom Gross kirjoitti pe kesäkuuta 12 20:17:50 2015 GMT+0300:

**Comment by datakurre** [comment]
This is related to https://github.com/plone/plone.app.mosaic/issues/61, because this is already possible with correct p.a.registry configuration, but easy way to do this is missing.

**Comment by datakurre** [comment]
The next release of collective.themefragments provides a new tile called "Theme fragment" for Mosaic. It allows rendering a selected theme fragment as tile. For example, with the following files / lines in theme

``./fragments/logo.pt``:

    <img src="logo.png" />

``./manifest.cfg``:

    [theme:themefragments:tiles]
    logo = Logo tile

one could place the results of ``logo.pt`` as a tile in Mosaic layout editor by inserting *Theme fragment tile* and selecting *Logo tile* from on its configuration form.

**Comment by vangheem** [comment]
For now, theme fragments or tinymce templates are the way to go for this. Closing this ticket as I don't think we're support an additional way to do snippets.

**Comment by djay** [comment]
Rapido also allows this with either python, zpt and/or format strings.
